In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/titanic_prepared.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Newfare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,10.8750
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,142.5666
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,11.8875
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,106.2000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,12.0750

pd.iterrows()

In [5]:
df["Gender"] = np.nan
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Newfare,Gender
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,10.8750,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,142.5666,NaN
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,11.8875,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,106.2000,NaN
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,12.0750,NaN

In [6]:
%%time

for index, row in df.iterrows():
    if row["Sex"] == "male":
        df.loc[index, "Gender"] = 1
    else:
        df.loc[index, "Gender"] = 0

CPU times: total: 78.1 ms
Wall time: 87.6 ms

pd.itertuples()

In [10]:
df["Gender"] = None
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Newfare,Gender
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,10.8750,None
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,142.5666,None
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,11.8875,None
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,106.2000,None
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,12.0750,None

In [8]:
%%time

for row in df.itertuples():
    if row.Sex == "male":
        df.loc[row.Index, "Gender"] = 1
    else:
        df.loc[row.Index, "Gender"] = 0

CPU times: total: 62.5 ms
Wall time: 60.2 ms

np.where()

In [9]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Newfare,Gender
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,10.8750,1.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,142.5666,0.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,11.8875,0.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,106.2000,0.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,12.0750,1.0

In [11]:
df["Gender"] = None
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Newfare,Gender
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,10.8750,None
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,142.5666,None
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,11.8875,None
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,106.2000,None
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,12.0750,None

In [12]:
%%time
df["Gender"] = np.where(df["Sex"] == "male", 1, 0)

CPU times: total: 0 ns
Wall time: 7.54 ms

pd.apply()

In [13]:
df["Gender"] = None

In [15]:
%%time
def gender_encoder(x):
    if x == "male":
        return 1
    else:
        return 0

df["Gender"] = df["Sex"].apply(gender_encoder)

CPU times: total: 0 ns
Wall time: 664 μs

In [16]:
df["Gender"] = None

In [17]:
df["Gender"] = df["Sex"].apply(lambda x: 1 if x == "male" else 0)

Pandarallel

In [19]:
!pip install pandarallel

Collecting pandarallel
  Downloading pandarallel-1.6.5.tar.gz (14 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting dill>=0.3.1 (from pandarallel)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas>=1 in C:\Users\monat\anaconda3\envs\ai\Lib\site-packages (from pandarallel) (3.0.3)
Requirement already satisfied: psutil in C:\Users\monat\anaconda3\envs\ai\Lib\site-packages (from pandarallel) (7.0.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\monat\anaconda3\envs\ai\Lib\site-packages (from pandas>=1->pandarallel) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\monat\anaconda3\envs\ai\Lib\site-packages (from pandas>=1->pandarallel) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\monat\anaconda3\envs\ai\Lib\site-packages (from pandas>=1->pandarallel) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\monat\anaconda3\envs\ai\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1->pandarallel) (1.17.0)
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Building wheels for collected packages: pandarallel
  Building wheel for pandarallel (pyproject.toml): started
  Building wheel for pandarallel (pyproject.toml): finished with status 'done'
  Created wheel for pandarallel: filename=pandarallel-1.6.5-py3-none-any.whl size=16730 sha256=c0f227a64494eeed5aabea947c276c20eabc996b7ad18e2692639985df776316
  Stored in directory: c:\users\monat\appdata\local\pip\cache\wheels\46\f9\0d\40c9cd74a7cb8dc8fe57e8d6c3c19e2c730449c0d3f2bf66b5
Successfully built pandarallel
Installing collected packages: dill, pandarallel

   -------------------- ------------------- 1/2 [pandarallel]
   ---------------------------------------- 2/2 [pandarallel]

Successfully installed dill-0.4.1 pandarallel-1.6.5

In [20]:
from pandarallel import pandarallel
pandarallel.initialize(progress_bar=True, nb_workers=4)

INFO: Pandarallel will run on 4 workers.
INFO: Pandarallel will use standard multiprocessing data transfer (pipe) to transfer data between the main process and workers.

WARNING: You are on Windows. If you detect any issue with pandarallel, be sure you checked out the Troubleshooting page:
https://nalepae.github.io/pandarallel/troubleshooting/

In [21]:
df["Gender"] = None

In [23]:
%%time
df["Gender"] = df["Sex"].parallel_apply(lambda x: 1 if x == "male" else 0)

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=221), Label(value='0 / 221'))), HB…

CPU times: total: 93.8 ms
Wall time: 1.43 s

TQDM

In [24]:
from tqdm import tqdm, trange

In [26]:
%%time

import time

for i in trange(50):
    time.sleep(0.1)
    pass

100%|██████████| 50/50 [00:05<00:00,  9.88it/s]

CPU times: total: 172 ms
Wall time: 5.06 s

In [31]:
%%time

tqdm.pandas(desc="Processing rows")

def gender_encoder(x):
    if x == "male":
        return 1
    else:
        return 0

df["Gender"] = df["Sex"].progress_apply(gender_encoder)

Processing rows: 100%|██████████| 881/881 [00:00<?, ?it/s]

CPU times: total: 0 ns
Wall time: 8.95 ms