Loan NN modeling

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [2]:
df= pd.read_csv("../data/loan_encoded.csv")
df.head()

    Loan_ID  Gender  ...  Property_Area_Semiurban  Property_Area_Urban
0  LP001002       1  ...                      0.0                  1.0
1  LP001003       1  ...                      0.0                  0.0
2  LP001005       1  ...                      0.0                  1.0
3  LP001006       1  ...                      0.0                  1.0
4  LP001008       1  ...                      0.0                  1.0

[5 rows x 15 columns]

In [3]:
df.isna().sum()

Loan_ID                     0
Gender                      0
Married                     0
Dependents                  0
Education                   0
Self_Employed               0
ApplicantIncome             0
CoapplicantIncome           0
LoanAmount                  0
Loan_Amount_Term            0
Credit_History              0
Loan_Status                 0
Property_Area_Rural        11
Property_Area_Semiurban    11
Property_Area_Urban        11
dtype: int64

In [4]:
df.shape

(603, 15)

In [5]:
df["Property_Area_Rural"] = df["Property_Area_Rural"].ffill()
df["Property_Area_Semiurban"] = df["Property_Area_Semiurban"].ffill()
df["Property_Area_Urban"] = df["Property_Area_Urban"].ffill()

In [6]:
df.isna().sum()

Loan_ID                    0
Gender                     0
Married                    0
Dependents                 0
Education                  0
Self_Employed              0
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                 0
Loan_Amount_Term           0
Credit_History             0
Loan_Status                0
Property_Area_Rural        0
Property_Area_Semiurban    0
Property_Area_Urban        0
dtype: int64

Feature Selection

In [7]:
df.drop(columns=["Loan_ID"], inplace=True)
df.head()

   Gender  Married  ...  Property_Area_Semiurban  Property_Area_Urban
0       1        0  ...                      0.0                  1.0
1       1        1  ...                      0.0                  0.0
2       1        1  ...                      0.0                  1.0
3       1        1  ...                      0.0                  1.0
4       1        0  ...                      0.0                  1.0

[5 rows x 14 columns]

MinMax Scaler

In [8]:
columns_to_scale = ["ApplicantIncome", "CoapplicantIncome", "LoanAmount", "Loan_Amount_Term"]

scaler = MinMaxScaler(clip=True)
df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

df.head()

   Gender  Married  ...  Property_Area_Semiurban  Property_Area_Urban
0       1        0  ...                      0.0                  1.0
1       1        1  ...                      0.0                  0.0
2       1        1  ...                      0.0                  1.0
3       1        1  ...                      0.0                  1.0
4       1        0  ...                      0.0                  1.0

[5 rows x 14 columns]

Training NN model