Load Iris data and visualize it

In [23]:
import pandas as pd
from sklearn.datasets import load_iris
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
import pickle

In [3]:
data = load_iris()
df = pd.DataFrame(data=data.data, columns= data.feature_names)
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
df["Species"]= data.target
df["Species_Name"] = df["Species"].map(lambda species: data.target_names[species])
df.head()

   sepal length (cm)  sepal width (cm)  ...  Species  Species_Name
0                5.1               3.5  ...        0        setosa
1                4.9               3.0  ...        0        setosa
2                4.7               3.2  ...        0        setosa
3                4.6               3.1  ...        0        setosa
4                5.0               3.6  ...        0        setosa

[5 rows x 6 columns]

In [6]:
df.head(70)

    sepal length (cm)  sepal width (cm)  ...  Species  Species_Name
0                 5.1               3.5  ...        0        setosa
1                 4.9               3.0  ...        0        setosa
2                 4.7               3.2  ...        0        setosa
3                 4.6               3.1  ...        0        setosa
4                 5.0               3.6  ...        0        setosa
..                ...               ...  ...      ...           ...
65                6.7               3.1  ...        1    versicolor
66                5.6               3.0  ...        1    versicolor
67                5.8               2.7  ...        1    versicolor
68                6.2               2.2  ...        1    versicolor
69                5.6               2.5  ...        1    versicolor

[70 rows x 6 columns]

Check missing values

In [7]:
df.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
Species              0
Species_Name         0
dtype: int64

In [8]:
df.dtypes

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
Species                int64
Species_Name             str
dtype: object

In [9]:
df = df.astype({"Species": "category"})
df.dtypes

sepal length (cm)     float64
sepal width (cm)      float64
petal length (cm)     float64
petal width (cm)      float64
Species              category
Species_Name              str
dtype: object

In [10]:
df.describe()

       sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count         150.000000        150.000000         150.000000        150.000000
mean            5.843333          3.057333           3.758000          1.199333
std             0.828066          0.435866           1.765298          0.762238
min             4.300000          2.000000           1.000000          0.100000
25%             5.100000          2.800000           1.600000          0.300000
50%             5.800000          3.000000           4.350000          1.300000
75%             6.400000          3.300000           5.100000          1.800000
max             7.900000          4.400000           6.900000          2.500000

In [11]:
#Histogram
fig = px.histogram(df, x="Species")
fig.show()

In [12]:
#Boxplot
fig = px.box(df, x=["sepal length (cm)", "sepal width (cm)", "petal length (cm)", "petal width (cm)"]
                   ,color="Species_Name")
fig.show()

In [13]:
fig = px.violin(df, y=["sepal length (cm)", "sepal width (cm)", "petal length (cm)", "petal width (cm)"]
                   ,color="Species_Name", points="all", box=False)
fig.show()

In [ ]:
#Scatter plot
fig = px.scatter(df, x="sepal length (cm)", y="sepal width (cm)", color="Species_Name")
fig.show()

In [16]:
fig = px.scatter(df, x="petal length (cm)", y="petal width (cm)", color="Species_Name")
fig.show()

In [18]:
fig = px.scatter_3d(df, x="petal length (cm)", y="petal width (cm)", z= "sepal length (cm)", 
                    color="Species_Name", height=500)
fig.show()

In [19]:
df.head()

   sepal length (cm)  sepal width (cm)  ...  Species  Species_Name
0                5.1               3.5  ...        0        setosa
1                4.9               3.0  ...        0        setosa
2                4.7               3.2  ...        0        setosa
3                4.6               3.1  ...        0        setosa
4                5.0               3.6  ...        0        setosa

[5 rows x 6 columns]

Standard Scaler

In [21]:
columns_to_scale = ["sepal length (cm)", "sepal width (cm)", "petal width (cm)", "petal length (cm)"]

scaler = StandardScaler()
df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

In [22]:
df.describe()

       sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
count       1.500000e+02      1.500000e+02       1.500000e+02      1.500000e+02
mean       -4.736952e-16     -7.815970e-16      -4.263256e-16     -4.736952e-16
std         1.003350e+00      1.003350e+00       1.003350e+00      1.003350e+00
min        -1.870024e+00     -2.433947e+00      -1.567576e+00     -1.447076e+00
25%        -9.006812e-01     -5.923730e-01      -1.226552e+00     -1.183812e+00
50%        -5.250608e-02     -1.319795e-01       3.364776e-01      1.325097e-01
75%         6.745011e-01      5.586108e-01       7.627583e-01      7.906707e-01
max         2.492019e+00      3.090775e+00       1.785832e+00      1.712096e+00

Train / Test Split