Movie Feature Engineering

In [2]:
import pandas as pd
import numpy as np
import re
from tqdm.notebook import tqdm

In [3]:
tqdm.pandas()

In [4]:
df = pd.read_csv("../data/movies.csv")
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MOVIES    9999 non-null   str
 1   YEAR      9355 non-null   str
 2   GENRE     9919 non-null   str
 3   RATING    8179 non-null   float64
 4   ONE-LINE  9999 non-null   str
 5   STARS     9999 non-null   str
 6   VOTES     8179 non-null   str
 7   RunTime   7041 non-null   float64
 8   Gross     460 non-null    str
dtypes: float64(2), str(7)
memory usage: 703.2 KB

## Data Cleaning

Year

In [6]:
df['YEAR'] = df['YEAR'].str.replace('(','',regex=False)
df['YEAR'] = df['YEAR'].str.replace(')','',regex=False)
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,2021–,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,2010–2022,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,2013–,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN

In [7]:
df['TYPE'] = np.where(df['YEAR'].str.contains('–'), 'Series', 'Movie')
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE
0,Blood Red Sky,2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN,Movie
1,Masters of the Universe: Revelation,2021–,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN,Series
2,The Walking Dead,2010–2022,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN,Series
3,Rick and Morty,2013–,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN,Series
4,Army of Thieves,2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN,Movie

In [8]:
df['YEAR_FROM'] = np.nan
df['YEAR_TO'] = np.nan

df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
0,Blood Red Sky,2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN,Movie,NaN,NaN
1,Masters of the Universe: Revelation,2021–,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN,Series,NaN,NaN
2,The Walking Dead,2010–2022,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN,Series,NaN,NaN
3,Rick and Morty,2013–,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN,Series,NaN,NaN
4,Army of Thieves,2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN,Movie,NaN,NaN

In [9]:
df.sample(15)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
6616,Bleach: Burîchi,2004–2012,"\nAnimation, Action, Adventure",7.6,"\nIchigo, Chad, Ishida and Orihime concentrate...","\n Directors:\nNoriyuki Abe, \nAkira Shimiz...",182,24.0,NaN,Series,NaN,NaN
765,Out of the Furnace,2013,"\nAction, Crime, Drama",6.8,\nWhen Rodney Baze mysteriously disappears and...,\n Director:\nScott Cooper\n| \n Stars:\...,"110,076",116.0,$11.33M,Movie,NaN,NaN
4672,One Hundred Years of Solitude,NaN,\nDrama,NaN,\nThe story of the Macondo city and five gener...,\n,NaN,NaN,NaN,Movie,NaN,NaN
6343,Graffiti Verité 3: A Voyage Into the Iconograp...,2000,"\nDocumentary, Music",NaN,\nThis experimental musical opus probes the so...,\n Director:\nBob Bryan\n| \n Stars:\nBr...,NaN,54.0,NaN,Movie,NaN,NaN
7235,Space Force,2020–,\nComedy,7.7,"\nWith the launch just days away, General Nair...",\n Director:\nDaina Reid\n| \n Stars:\nS...,"1,536",35.0,NaN,Series,NaN,NaN
6852,The Pentaverate,II,\nComedy,NaN,\nAdd a Plot\n,\n Director:\nTim Kirkby\n| \n Star:\nPh...,NaN,NaN,NaN,Movie,NaN,NaN
8187,Next in Fashion,2020,\nReality-TV,6.2,\nUrban reality meets next-level fantasy in a ...,"\n \n Stars:\nAlexa Chung, \nTan...",111,NaN,NaN,Movie,NaN,NaN
1301,Mystery Science Theater 3000,1988–1999,"\nComedy, Sci-Fi",8.5,\nIn the not-too-distant future Joel Robinson ...,"\n \n Stars:\nJoel Hodgson, \nMi...","23,491",92.0,NaN,Series,NaN,NaN
6780,Spirit Riding Free,2017–2019,"\nAnimation, Action, Adventure",8.2,\nAdd a Plot\n,"\n Directors:\nStephen Cooper, \nSean Mulle...",14,NaN,NaN,Series,NaN,NaN
9577,The Drew Barrymore Show,2020–,\nTalk-Show,NaN,"\n""Fake Doctors, Real Friends"" podcast hosts Z...","\n \n Stars:\nDrew Barrymore, \n...",NaN,44.0,NaN,Series,NaN,NaN
2875,La enfermedad del domingo,2018,\nDrama,6.9,\nA high-class old lady receives the unexpecte...,\n Director:\nRamón Salazar\n| \n Stars:...,"3,246",113.0,NaN,Movie,NaN,NaN
6125,Untitled Haiti Musical,NaN,"\nAnimation, Adventure, Comedy",NaN,\nBased on Wyclef Jean's life in Haiti.,\n,NaN,NaN,NaN,Movie,NaN,NaN
6904,Tiny House Nation,2014–,\nReality-TV,7.4,\nZack and John are in cowboy country as they ...,"\n \n Stars:\nJohn Weisbarth, \n...",23,40.0,NaN,Series,NaN,NaN
2256,The Lizzie Borden Chronicles,2015,"\nCrime, Drama, Horror",7.0,\nFictionalized account of actual events and p...,"\n \n Stars:\nChristina Ricci, \...","3,945",337.0,NaN,Movie,NaN,NaN
3100,Madaari,2016,"\nAdventure, Drama, Thriller",7.6,\nWhen Nirmal loses his family in a disaster c...,\n Director:\nNishikant Kamat\n| \n Star...,"13,823",133.0,NaN,Movie,NaN,NaN

In [10]:
def extract_from(x):
    if pd.isna(x):
        return np.nan
    
    year_to_return = None

    year = str(x)
    if '–' not in year:
        year_to_return = year
    else:
        # 2010-2015 -> [2010, 2015]
        # 2010- -> [2010,]
        years = year.split('–')
        year_to_return = years[0]

    year_to_return = re.sub('[^0-9]', '', year_to_return)

    return year_to_return


def extract_to(x):
    if pd.isna(x):
        return np.nan
    
    year_to_return = None

    year = str(x)
    if '–' not in year:
        year_to_return = re.sub('[^0-9]', '', year)
        return year_to_return
    else:
        years = year.split('–')
        year_to_return = re.sub('[^0-9]', '', years[1])
        if len(year_to_return) == 0:
            return np.nan
        else:
            return year_to_return
    

df['YEAR_FROM'] = df['YEAR'].progress_apply(extract_from)
df['YEAR_TO'] = df['YEAR'].progress_apply(extract_to)

  0%|          | 0/9999 [00:00<?, ?it/s]

  0%|          | 0/9999 [00:00<?, ?it/s]

In [11]:
df.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
4886,Piola,2019,\nDrama,6.4,\nTwo friends spend their time making rap musi...,\n Director:\nLuis Pérez García\n| \n St...,277,102.0,NaN,Movie,2019,2019
4017,Kekkon dekinai otoko,2006–,"\nComedy, Drama",7.6,\nA 40-year-old gifted architect enjoys living...,"\n \n Stars:\nHiroshi Abe, \nTak...",713,45.0,NaN,Series,2006,NaN
7937,The Umbrella Academy,2019–,"\nAction, Adventure, Comedy",8.6,\nAfter Five travels to 1982 to carry out his ...,\n Director:\nEllen Kuras\n| \n Stars:\n...,"3,012",47.0,NaN,Series,2019,NaN
7524,Power Rangers Beast Morphers,2019–2020,"\nAction, Adventure, Drama",7.3,\nThe Beast Morphers Rangers are hypnotized in...,\n Director:\nOliver Driver\n| \n Stars:...,30,NaN,NaN,Series,2019,2020
9869,Cobra Kai,2018–,"\nAction, Comedy, Drama",NaN,\nAdd a Plot\n,"\n \n Stars:\nRalph Macchio, \nW...",NaN,NaN,NaN,Series,2018,NaN
5346,Rezeta,2012,"\nComedy, Drama, Romance",5.7,\nRezeta tells the story of a jet-setting mode...,\n Director:\nFernando Frias\n| \n Stars...,508,85.0,NaN,Movie,2012,2012
7914,Explained,2018–,\nDocumentary,8.2,\nThe planet's current rate of meat consumptio...,\n \n Stars:\nVincent Kartheiser...,267,NaN,NaN,Series,2018,NaN
647,The Sandman,2021–,"\nAction, Adventure, Drama",NaN,\nUpon escaping after decades of imprisonment ...,\n \n Stars:\nVivienne Acheampon...,NaN,NaN,NaN,Series,2021,NaN
9930,Ginny & Georgia,2021–,"\nComedy, Drama",NaN,\nAdd a Plot\n,\n Director:\nAnya Adams\n| \n Stars:\nB...,NaN,NaN,NaN,Series,2021,NaN
4930,Kevin James: Never Don't Give Up,2018 TV Special,\nComedy,6.1,\nKevin James is back with a new stand-up spec...,\n Director:\nAndy Fickman\n| \n Star:\n...,"1,366",62.0,NaN,Movie,2018,2018

Genre

In [12]:
df['GENRE'] = df['GENRE'].str.replace(' ', '', regex=False)
df['GENRE'] = df['GENRE'].str.replace('\n', '', regex=False)
df.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
1912,The Knight Before Christmas,2019,"Adventure,Comedy,Drama",5.6,\nA medieval English knight is magically trans...,\n Director:\nMonika Mitchell\n| \n Star...,"15,522",92.0,NaN,Movie,2019,2019
4197,Fittest on Earth: The Story of the 2015 Reebok...,2016,"Documentary,Sport",7.1,\nThe fittest athletes on earth take on the Cr...,"\n Directors:\nHeber Cannon, \nMarston Sawy...","1,567",104.0,NaN,Movie,2016,2016
5655,Reggie Watts: Spatial,2016 TV Special,"Comedy,Music",6.1,\nCompletely improvised show weaving together ...,\n Director:\nBenjamin Dickinson\n| \n S...,480,61.0,NaN,Movie,2016,2016
7469,Hero Mask,2018–2019,"Animation,Action,Crime",6.1,\nConnor and Creighton break into Herst's hous...,\n Director:\nHiroyasu Aoki\n| \n Stars:...,14,24.0,NaN,Series,2018,2019
3377,Transformers: Rescue Bots Academy,2019–,"Animation,Action,Adventure",6.6,\nFive students of the Rescue Bots Training Ac...,"\n \n Stars:\nTodd Perlmutter, \...",76,11.0,NaN,Series,2019,NaN
6128,The Whole World is Watching: Inside Aaron Sork...,2021 TV Special,NaN,NaN,\nAdd a Plot\n,\n \n Stars:\nYahya Abdul-Mateen...,NaN,28.0,NaN,Movie,2021,2021
7786,Virgin River,2019–,"Drama,Romance",7.6,\nThe town attends the annual picnic where res...,\n Director:\nGail Harvey\n| \n Stars:\n...,332,43.0,NaN,Series,2019,NaN
2867,Dead in Tombstone,2013 Video,"Action,Fantasy,Horror",4.9,"\nA leader killed by his own gang, gets offere...",\n Director:\nRoel Reiné\n| \n Stars:\nD...,"5,271",100.0,NaN,Movie,2013,2013
3529,Loose Change 9/11: An American Coup,2009 Video,"Documentary,History,War",7.1,\nAn exploration of the viewpoint that the Sep...,\n Director:\nDylan Avery\n| \n Stars:\n...,"3,517",99.0,NaN,Movie,2009,2009
9523,Too Hot to Handle,2020–,"Game-Show,Reality-TV,Romance",5.4,"\nThe smokin' hot singles start mingling, thin...","\n \n Stars:\nMarvin Anthony, \n...",131,45.0,NaN,Series,2020,NaN

In [13]:
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
0,Blood Red Sky,2021,"Action,Horror,Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN,Movie,2021,2021
1,Masters of the Universe: Revelation,2021–,"Animation,Action,Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN,Series,2021,NaN
2,The Walking Dead,2010–2022,"Drama,Horror,Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN,Series,2010,2022
3,Rick and Morty,2013–,"Animation,Adventure,Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN,Series,2013,NaN
4,Army of Thieves,2021,"Action,Crime,Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN,Movie,2021,2021

In [14]:
df_dummy = df['GENRE'].str.get_dummies(sep=',')
df_dummy = df_dummy.add_prefix('GENRE_')
df_dummy.head()

,GENRE_Action,GENRE_Adventure,GENRE_Animation,GENRE_Biography,GENRE_Comedy,GENRE_Crime,GENRE_Documentary,GENRE_Drama,GENRE_Family,GENRE_Fantasy,...,GENRE_News,GENRE_Reality-TV,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
df_dummy.shape

(9999, 27)

In [16]:
df.shape

(9999, 12)

In [17]:
#Join/Merge the dummy dataframe with the original dataframe
#df = df.join(df_dummy)
df = df.merge(df_dummy, left_index=True, right_index=True)
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,GENRE_News,GENRE_Reality-TV,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western
0,Blood Red Sky,2021,"Action,Horror,Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN,Movie,...,0,0,0,0,0,0,0,1,0,0
1,Masters of the Universe: Revelation,2021–,"Animation,Action,Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
2,The Walking Dead,2010–2022,"Drama,Horror,Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN,Series,...,0,0,0,0,0,0,0,1,0,0
3,Rick and Morty,2013–,"Animation,Adventure,Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
4,Army of Thieves,2021,"Action,Crime,Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0

Stars

In [18]:
df.sample(15)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,GENRE_News,GENRE_Reality-TV,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western
8146,The Witcher,2019–,"Action,Adventure,Fantasy",NaN,\nAdd a Plot\n,\n Director:\nEdward Bazalgette\n| \n St...,NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
6080,A Note of Explanation,NaN,NaN,NaN,\nA time-travelling sprite who inhabits the do...,\n,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
5205,Watergate,I,"Action,Crime,Drama",NaN,\nA look at the events and historical figures ...,\n,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
4749,De Familie Claus,2020,"Comedy,Family,Fantasy",5.8,\nAfter discovering his grandfather is Santa C...,\n Director:\nMatthias Temmermans\n| \n ...,720,96.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
2224,Abzurdah,2015,"Biography,Drama,Romance",5.4,"\nCielo, a wealthy middle-class teenager, meet...",\n Director:\nDaniela Goggi\n| \n Stars:...,"1,945",90.0,NaN,Movie,...,0,0,1,0,0,0,0,0,0,0
6824,Street Food: Asia,2019,Documentary,7.8,\nTofu pudding. Fish head soup. Goat stew. The...,"\n \n Stars:\nCaitlyn Elizabeth,...",160,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
7480,Marianne,2019,"Drama,Horror,Mystery",7.6,\nTonio makes a disturbing discovery at the sh...,\n Director:\nSamuel Bodin\n| \n Stars:\...,530,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
2270,Shéhérazade,2018,"Drama,Romance,Thriller",7.1,"\nZachary, 17 years old, gets out of jail. Rej...",\n Director:\nJean-Bernard Marlin\n| \n ...,"1,810",109.0,NaN,Movie,...,0,0,1,0,0,0,0,1,0,0
6308,Graffiti Verité 6: The Odyssey,2006 Video,Documentary,NaN,\nExamines and reveals the truth behind 31 Mul...,\n Director:\nBob Bryan\n| \n Stars:\nAs...,NaN,72.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
9607,Formula 1: Drive to Survive,2019–,"Documentary,Sport",8.6,\nPierre Gasly's performances have been outsta...,"\n \n Stars:\nAlexander Albon, \...",646,37.0,NaN,Series,...,0,0,0,0,0,1,0,0,0,0
573,Sweet Girl,2021,"Action,Drama,Thriller",NaN,\nA devastated husband vows to bring justice t...,\n Director:\nBrian Andrew Mendoza\n| \n ...,NaN,96.0,NaN,Movie,...,0,0,0,0,0,0,0,1,0,0
2707,Private Life,2020,"Crime,Drama,Romance",6.6,"\nIn a world where data is no longer private, ...","\n \n Stars:\nSeohyun, \nHyo-jin...",498,70.0,NaN,Movie,...,0,0,1,0,0,0,0,0,0,0
8591,Carmen Sandiego,2019–2021,"Animation,Action,Adventure",8.3,\nCarmen searches for clues to her mother's id...,"\n Directors:\nJos Humphrey, \nKevin Dart\n...",94,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
5178,KidPoker,2015 TV Movie,"Documentary,Biography,Sport",6.8,"\nDaniel Negreanu, the man, the legend, and th...","\n Directors:\nGary Davis, \nFrancine Watso...",723,89.0,NaN,Movie,...,0,0,0,0,0,1,0,0,0,0
5964,The 50th Law,NaN,Biography,NaN,\nFollows 50 Cent's rise as both a young urban...,\n,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0

In [19]:
df['STARS'] = df['STARS'].str.replace('\n', '', regex=False)
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,GENRE_News,GENRE_Reality-TV,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western
0,Blood Red Sky,2021,"Action,Horror,Thriller",6.1,\nA woman with a mysterious illness is forced ...,Director:Peter Thorwarth| Stars:Peri B...,"21,062",121.0,NaN,Movie,...,0,0,0,0,0,0,0,1,0,0
1,Masters of the Universe: Revelation,2021–,"Animation,Action,Adventure",5.0,\nThe war for Eternia begins again in what may...,"Stars:Chris Wood, Sarah Michel...","17,870",25.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
2,The Walking Dead,2010–2022,"Drama,Horror,Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"Stars:Andrew Lincoln, Norman R...","885,805",44.0,NaN,Series,...,0,0,0,0,0,0,0,1,0,0
3,Rick and Morty,2013–,"Animation,Adventure,Comedy",9.2,\nAn animated series that follows the exploits...,"Stars:Justin Roiland, Chris Pa...","414,849",23.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
4,Army of Thieves,2021,"Action,Crime,Horror",NaN,"\nA prequel, set before the events of Army of ...",Director:Matthias Schweighöfer| Stars:...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0

In [20]:
df["Directors"] = None
df["Actors"] = None

def extract_directors(x):
    if "Director" in x:
        stars = x.split("|")
        if "Director" in stars[0]:
            return stars[0]
        else:
            return stars[1]
    else:
        return np.nan

def extract_actors(x):
    if "Star" in x:
        stars = x.split("|")
        if "Star" in stars[0]:
            return stars[0]
        else:
            return stars[1]
    else:
        return np.nan
    
df["Directors"] = df["STARS"].progress_apply(extract_directors)
df["Actors"] = df["STARS"].progress_apply(extract_actors)

df.head()

  0%|          | 0/9999 [00:00<?, ?it/s]

  0%|          | 0/9999 [00:00<?, ?it/s]

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western,Directors,Actors
0,Blood Red Sky,2021,"Action,Horror,Thriller",6.1,\nA woman with a mysterious illness is forced ...,Director:Peter Thorwarth| Stars:Peri B...,"21,062",121.0,NaN,Movie,...,0,0,0,0,0,1,0,0,Director:Peter Thorwarth,"Stars:Peri Baumeister, Carl Anton Koch, A..."
1,Masters of the Universe: Revelation,2021–,"Animation,Action,Adventure",5.0,\nThe war for Eternia begins again in what may...,"Stars:Chris Wood, Sarah Michel...","17,870",25.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Stars:Chris Wood, Sarah Michel..."
2,The Walking Dead,2010–2022,"Drama,Horror,Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"Stars:Andrew Lincoln, Norman R...","885,805",44.0,NaN,Series,...,0,0,0,0,0,1,0,0,NaN,"Stars:Andrew Lincoln, Norman R..."
3,Rick and Morty,2013–,"Animation,Adventure,Comedy",9.2,\nAn animated series that follows the exploits...,"Stars:Justin Roiland, Chris Pa...","414,849",23.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Stars:Justin Roiland, Chris Pa..."
4,Army of Thieves,2021,"Action,Crime,Horror",NaN,"\nA prequel, set before the events of Army of ...",Director:Matthias Schweighöfer| Stars:...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,Director:Matthias Schweighöfer,"Stars:Matthias Schweighöfer, Nathalie Emm..."

In [21]:
df.sample(15)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western,Directors,Actors
4728,DeMarcus Family Rules,2020–,Reality-TV,6.2,\nRascal Flatts bassist Jay DeMarcus and ex-be...,"Stars:Jane Alderson, Chris Cha...",90,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Stars:Jane Alderson, Chris Cha..."
1003,Super Dark Times,2017,"Crime,Drama,Horror",6.6,\nTeenagers Zach and Josh have been best frien...,Director:Kevin Phillips| Stars:Owen Ca...,"20,965",103.0,$0.03M,Movie,...,0,0,0,0,0,0,0,0,Director:Kevin Phillips,"Stars:Owen Campbell, Charlie Tahan, Eliza..."
9314,Dad Stop Embarrassing Me,2021,"Comedy,Family",5.7,"\nAfter Sasha moves in with Brian, a mortifyin...",Director:Ken Whittingham| Stars:Jamie ...,98,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,Director:Ken Whittingham,"Stars:Jamie Foxx, David Alan Grier, Kyla-..."
7424,The Umbrella Academy,2019–,"Action,Adventure,Comedy",8.4,"\nAs the sit-in approaches, Allison reconnects...",Director:Stephen Surjik| Stars:Elliot ...,"3,120",48.0,NaN,Series,...,0,0,0,0,0,0,0,0,Director:Stephen Surjik,"Stars:Elliot Page, Tom Hopper, David Cast..."
8887,Transformers: War for Cybertron,2020–2021,"Animation,Action,Adventure",6.6,\nMegatron's continued use of the Golden Disk ...,"Directors:Takashi Kamei, Kazuma Shimizu| ...",53,26.0,NaN,Series,...,0,0,0,0,0,0,0,0,"Directors:Takashi Kamei, Kazuma Shimizu","Stars:Jason Marnocha, Jake Foushee, Justi..."
9880,Cobra Kai,2018–,"Action,Comedy,Drama",NaN,\nAdd a Plot\n,"Stars:Ralph Macchio, William Z...",NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Stars:Ralph Macchio, William Z..."
2704,The Goop Lab,2020–,"Documentary,Reality-TV",2.5,"\nLeading with curiosity, Gwyneth Paltrow and ...","Stars:Gwyneth Paltrow, Elise L...","3,004",30.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Stars:Gwyneth Paltrow, Elise L..."
2733,Pramface,2012–2014,Comedy,7.5,\nA girl from a middle-class family gets drunk...,"Stars:Sean Verey, Scarlett Ali...","2,408",NaN,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Stars:Sean Verey, Scarlett Ali..."
9716,Jiok,2021–,"Drama,Fantasy,Horror",NaN,\nAdd a Plot\n,Director:Sang-ho Yeon| Stars:Yoo Ah-in...,NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,Director:Sang-ho Yeon,"Stars:Yoo Ah-in, Kim Hyun-joo, Jeong Min ..."
7049,Fuller House,2016–2020,"Comedy,Family",7.5,\nRamona introduces Rocki to Ethan and she sus...,Director:Candace Cameron Bure| Stars:C...,183,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,Director:Candace Cameron Bure,"Stars:Candace Cameron Bure, Jodie Sweetin..."
9899,Dexter,2006–2013,"Crime,Drama,Mystery",8.5,\nDexter wonders if his father's Code is truly...,Director:Ernest R. Dickerson| Stars:Mi...,"3,591",54.0,NaN,Series,...,0,0,0,0,0,0,0,0,Director:Ernest R. Dickerson,"Stars:Michael C. Hall, Julie Benz, Jennif..."
7702,Lucifer,2016–2021,"Crime,Drama,Fantasy",6.6,\nThe year is 1946. The world is black and whi...,"Director:Viet Nguyen| Stars:Tom Ellis,...","4,319",55.0,NaN,Series,...,0,0,0,0,0,0,0,0,Director:Viet Nguyen,"Stars:Tom Ellis, Lauren German, Kevin Ale..."
2510,Minecraft: Story Mode,2018,Adventure,5.7,"\nMInecraft: Story Mode is an interactive, ani...","Stars:Patton Oswalt, Catherine...",181,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,NaN,"Stars:Patton Oswalt, Catherine..."
8942,You Don't Know Me,NaN,Drama,NaN,\nAdd a Plot\n,Director:Sarmad Masud| Stars:Samuel Ad...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,Director:Sarmad Masud,"Stars:Samuel Adewunmi, Saskia Chana, Soph..."
7525,Ginny & Georgia,2021–,"Comedy,Drama",7.5,\nHunter's aloofness makes Ginny insecure; Max...,Director:Renuka Jeyapalan| Stars:Brian...,525,51.0,NaN,Series,...,0,0,0,0,0,0,0,0,Director:Renuka Jeyapalan,"Stars:Brianne Howey, Antonia Gentry, Dies..."

In [22]:
df["Directors"] = df["Directors"].str.replace('Director:', '', regex=False)
df["Directors"] = df["Directors"].str.replace('Directors:', '', regex=False)
df["Actors"] = df["Actors"].str.replace('Star:', '', regex=False)
df["Actors"] = df["Actors"].str.replace('Stars:', '', regex=False)
df.head(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western,Directors,Actors
0,Blood Red Sky,2021,"Action,Horror,Thriller",6.1,\nA woman with a mysterious illness is forced ...,Director:Peter Thorwarth| Stars:Peri B...,"21,062",121.0,NaN,Movie,...,0,0,0,0,0,1,0,0,Peter Thorwarth,"Peri Baumeister, Carl Anton Koch, Alexand..."
1,Masters of the Universe: Revelation,2021–,"Animation,Action,Adventure",5.0,\nThe war for Eternia begins again in what may...,"Stars:Chris Wood, Sarah Michel...","17,870",25.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Chris Wood, Sarah Michelle Gel..."
2,The Walking Dead,2010–2022,"Drama,Horror,Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"Stars:Andrew Lincoln, Norman R...","885,805",44.0,NaN,Series,...,0,0,0,0,0,1,0,0,NaN,"Andrew Lincoln, Norman Reedus,..."
3,Rick and Morty,2013–,"Animation,Adventure,Comedy",9.2,\nAn animated series that follows the exploits...,"Stars:Justin Roiland, Chris Pa...","414,849",23.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Justin Roiland, Chris Parnell,..."
4,Army of Thieves,2021,"Action,Crime,Horror",NaN,"\nA prequel, set before the events of Army of ...",Director:Matthias Schweighöfer| Stars:...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,Matthias Schweighöfer,"Matthias Schweighöfer, Nathalie Emmanuel,..."
5,Outer Banks,2020–,"Action,Crime,Drama",7.6,\nA group of teenagers from the wrong side of ...,"Stars:Chase Stokes, Madelyn Cl...","25,858",50.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Chase Stokes, Madelyn Cline, M..."
6,The Last Letter from Your Lover,2021,"Drama,Romance",6.8,\nA pair of interwoven stories set in the past...,Director:Augustine Frizzell| Stars:Sha...,"5,283",110.0,NaN,Movie,...,1,0,0,0,0,0,0,0,Augustine Frizzell,"Shailene Woodley, Joe Alwyn, Wendy Nottin..."
7,Dexter,2006–2013,"Crime,Drama,Mystery",8.6,"\nBy day, mild-mannered Dexter is a blood-spat...","Stars:Michael C. Hall, Jennife...","665,387",53.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Michael C. Hall, Jennifer Carp..."
8,Never Have I Ever,2020–,Comedy,7.9,\nThe complicated life of a modern-day first g...,"Stars:Maitreyi Ramakrishnan, P...","34,530",30.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Maitreyi Ramakrishnan, Poorna ..."
9,Virgin River,2019–,"Drama,Romance",7.4,"\nSeeking a fresh start, nurse practitioner Me...","Stars:Alexandra Breckenridge, ...","27,279",44.0,NaN,Series,...,1,0,0,0,0,0,0,0,NaN,"Alexandra Breckenridge, Martin..."

Dummy on Actors

In [23]:
df["Actors"] = df["Actors"].str.replace(", ", ",", regex=False)
df["Actors"] = df["Actors"].str.strip()

df_dummy = df['Actors'].str.get_dummies(sep=',')
df_dummy = df_dummy.add_prefix('Actor_')
df_dummy.head()

,Actor_2 Chainz,Actor_2'Live Bre,Actor_2Mex,Actor_50 Cent,Actor_A Boogie wit da Hoodie,Actor_A.J. Baime,Actor_A.J. Daulerio,Actor_A.J. LoCascio,Actor_A.N.T.I.,Actor_AJ Bowen,...,Actor_Özge Borak,Actor_Özge Özpirinçci,Actor_Özgür Emre Yildirim,Actor_Özgür Ozan,Actor_Özkan Ugur,Actor_Özz Nûjen,Actor_Úrsula Corberó,Actor_Úrsula Pruneda,Actor_Ülkü Duru,Actor_Þorsteinn Bachmann
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
df_dummy.shape

(9999, 17325)

In [25]:
#merge/join the dummy dataframe with the original dataframe
df = df.merge(df_dummy, left_index=True, right_index=True)
df.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,Actor_Özge Borak,Actor_Özge Özpirinçci,Actor_Özgür Emre Yildirim,Actor_Özgür Ozan,Actor_Özkan Ugur,Actor_Özz Nûjen,Actor_Úrsula Corberó,Actor_Úrsula Pruneda,Actor_Ülkü Duru,Actor_Þorsteinn Bachmann
2468,Annyeong? Naya!,2021–,"Comedy,Fantasy,Romance",7.2,"\nMiserable and unsuccessful, a woman thinks s...","Stars:Kang-hee Choi, Kim Young...",344,65.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
135,Star Wars: The Clone Wars,2008–2020,"Animation,Action,Adventure",8.3,\nJedi Knights lead the Grand Army of the Repu...,"Stars:Tom Kane, Dee Bradley Ba...","71,904",23.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
1791,I'll Be Home for Christmas,2016 TV Movie,"Drama,Family,Romance",6.1,"\nJackie Foster (Suvari), is a dynamic Assista...",Director:James Brolin| Stars:James Bro...,"2,150",84.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
9461,True Story,III,"Comedy,Drama",NaN,\nAdd a Plot\n,Director:Stephen Williams| Stars:Kevin...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
2793,Shaitan,2011,"Action,Crime,Drama",7.2,\nFive substance-abusing friends decide to fak...,Director:Bejoy Nambiar| Stars:Kalki Ko...,"8,238",121.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
9911,Pretty Smart,NaN,Comedy,NaN,\nAdd a Plot\n,Director:Jody Margolin Hahn| Stars:Cin...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
7075,Aseudal Yeondaegi,2019–,"Action,Drama,Fantasy",8.9,\nAdd a Plot\n,Director:Won Suk Kim| Stars:Song Joong...,146,80.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
5829,U-Prince: The Playful Comm-Arts,2016,Romance,8.5,"\nSung dreams of making Kiran, from the comm-a...","Stars:Korawit Boonsri, Phumpho...",22,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
2277,Brotherly Love,III 2015,Drama,6.7,\nSet on the backdrop of Philadelphia's famed ...,Director:Jamal Hill| Stars:Keke Palmer...,"1,787",89.0,$0.44M,Movie,...,0,0,0,0,0,0,0,0,0,0
5470,Niquelao!,2019–,Reality-TV,5.5,\nPatisserie Chef Christian Escribà co-present...,"Stars:Pepa Charro, Christian E...",84,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0

Dummy on Director

In [26]:
df["Directors"] = df["Directors"].str.replace(", ", ",", regex=False)
df["Directors"] = df["Directors"].str.strip()

df_dummy = df['Directors'].str.get_dummies(sep=',')
df_dummy = df_dummy.add_prefix('Director_')
df_dummy.head()

,Director_Aadish Keluskar,Director_Aaron Augenblick,Director_Aaron Burns,Director_Aaron Hann,Director_Aaron Lieber,Director_Aaron Long,Director_Aaron Moorhead,Director_Aaron Saidman,Director_Aaron Sorkin,Director_Aban Raza,...,Director_Àlex Pastor,Director_Álex de la Iglesia,Director_Álvaro Brechner,Director_Álvaro Fernández Armero,Director_Álvaro Longoria,Director_Ángel Gómez Hernández,Director_Ángeles Reiné,Director_Åke Sandgren,Director_Óscar Pedraza,Director_Ömer Ugur
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
#merge the dummy dataframe with the original dataframe
df = df.merge(df_dummy, left_index=True, right_index=True)
df.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,Director_Àlex Pastor,Director_Álex de la Iglesia,Director_Álvaro Brechner,Director_Álvaro Fernández Armero,Director_Álvaro Longoria,Director_Ángel Gómez Hernández,Director_Ángeles Reiné,Director_Åke Sandgren,Director_Óscar Pedraza,Director_Ömer Ugur
2889,Re: Mind,2017–2018,"Mystery,Thriller",5.0,\n11 Japanese school girls awaken bound to the...,"Stars:Mirei Sasaki, Sarina Ush...","1,337",30.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
8102,The Circle,2020–,"Game-Show,Reality-TV",7.7,\nAn anonymous game of Ask Me Anything leads t...,"Stars:Michelle Buteau, Miranda...",155,44.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
5524,Cristela Alonzo: Lower Classy,2017 TV Special,Comedy,6.4,\nShe's no stranger to breaking glass ceilings...,Director:Marcus Raboy| Star:Cristela A...,805,66.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
5938,Bigflo & Oli: Hip Hop Frenzy,2020,"Documentary,Music",6.8,"\nIn this intimate documentary, follow the Fre...","Directors:Jérémie Levypon, Florian Ordonez...",102,100.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
7698,Anne,2017–2019,"Drama,Family",9.2,\nA dance rehearsal generates sparks (and tens...,Director:Paul Fox| Stars:Amybeth McNul...,"1,556",44.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
5441,TUNA Girl,2019,"Comedy,Drama",5.8,\nA clumsy but cheerful fisheries student stru...,Director:Mana Yasuda| Stars:Tom Fujita...,121,89.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
4412,StoryBots Super Songs,2016–,"Animation,Family,Musical",8.5,"\nBased on the award-winning educational apps,...","Stars:Judy Greer, Erin Fitzger...",150,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
2256,The Lizzie Borden Chronicles,2015,"Crime,Drama,Horror",7.0,\nFictionalized account of actual events and p...,"Stars:Christina Ricci, Clea Du...","3,945",337.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
5504,Black Heart,2014,Drama,6.5,\nBlaming a crooked media mogul for the death ...,,41,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
2474,Nicky Jam: El Ganador,2018–,"Biography,Music",7.8,\nA look at the life and career of the Latin m...,"Stars:Nicky Jam, Jose Caro, Da...","1,030",45.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0

In [28]:
df.shape

(9999, 21449)

In [29]:
df.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,Director_Àlex Pastor,Director_Álex de la Iglesia,Director_Álvaro Brechner,Director_Álvaro Fernández Armero,Director_Álvaro Longoria,Director_Ángel Gómez Hernández,Director_Ángeles Reiné,Director_Åke Sandgren,Director_Óscar Pedraza,Director_Ömer Ugur
4021,The Magic Order,NaN,"Action,Adventure,Drama",NaN,\nFive families with magical abilities secretl...,Star:Cameryn Colt,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
8283,Love Is Blind,2020–,"Reality-TV,Romance",6.3,\nEmotions run high as the couples plan for th...,Director:Brian Smith| Stars:Nick Lache...,129,55.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
1734,Gabby's Dollhouse,2021–,"Animation,Adventure,Comedy",7.1,\nThis colorful series leads preschoolers room...,"Stars:Laila Lockhart Kraner, T...",173,24.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
9260,The Umbrella Academy,2019–,"Action,Adventure,Comedy",NaN,\nAdd a Plot\n,"Stars:Elliot Page, Tom Hopper,...",NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
4308,Buddy Thunderstruck,2017,"Animation,Action,Comedy",7.8,\nThe hard-driving trucking adventures of a do...,"Stars:Brian Atkinson, Debi Der...",467,24.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
1070,Hotel Del Luna,2019,"Drama,Fantasy,Horror",8.2,\nWhen he's invited to manage a hotel for dead...,"Stars:Ji-eun Lee, Yeo Jin-gu, ...","4,854",80.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
7332,Ask 101,2020–,"Comedy,Drama,Romance",7.6,\nThe teachers offer the group one last chance...,Director:Deniz Yorulmazer| Stars:Kubil...,344,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
7291,3Below: Tales of Arcadia,2018–2019,"Animation,Action,Adventure",8.5,\nWith General Morando searching for Gaylen's ...,Director:Rodrigo Blaas| Stars:Tatiana ...,142,22.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
4181,The Director: An Evolution in Three Acts,2013,Documentary,6.2,\nA look at the life and work of Gucci fashion...,Director:Christina Voros| Stars:Frida ...,213,85.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
2964,Oorlogswinter,2008,"Drama,History,War",7.0,"\nIn the Nazi-occupied Netherlands, a teenage ...",Director:Martin Koolhoven| Stars:Marti...,"12,479",103.0,$0.54M,Movie,...,0,0,0,0,0,0,0,0,0,0

One-Line

In [30]:
df["ONE-LINE"] = df["ONE-LINE"].str.replace('\n', '', regex=False)
df["ONE-LINE"] = np.where(df["ONE-LINE"] == "Add a Plot", np.nan, df["ONE-LINE"])
df.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,Director_Àlex Pastor,Director_Álex de la Iglesia,Director_Álvaro Brechner,Director_Álvaro Fernández Armero,Director_Álvaro Longoria,Director_Ángel Gómez Hernández,Director_Ángeles Reiné,Director_Åke Sandgren,Director_Óscar Pedraza,Director_Ömer Ugur
5830,Novatos,2015,Drama,4.8,Hazing (Novatos) a feature film based on the d...,Director:Pablo Aragüés| Stars:Nicolás ...,257,92.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
4059,The Oscars,2018 TV Special,Music,5.7,"The 90th Annual Academy Awards ceremony, hoste...",Director:Glenn Weiss| Stars:Jimmy Kimm...,"1,475",187.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
113,South Park,1997–,"Animation,Comedy",8.7,Follows the misadventures of four irreverent g...,"Stars:Trey Parker, Matt Stone,...","340,148",22.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
3289,The Oscars,2016 TV Special,Music,6.4,The 88th Academy Awards ceremony honors achiev...,Director:Glenn Weiss| Stars:Chris Rock...,"2,063",175.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
2904,Duck Duck Goose,I 2018,"Animation,Adventure,Comedy",5.8,A bachelor goose must form a bond with two los...,Director:Christopher Jenkins| Stars:Ji...,"3,335",91.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
4982,Salam - The First ****** Nobel Laureate,2018,Documentary,7.9,"""Salam"" is a feature length documentary about ...",Director:Anand Kamalakar,371,75.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
8697,Baki,2018–2020,"Animation,Action,Drama",8.0,He who wins this match will be the strongest m...,Director:Toshiki Hirano| Stars:Troy Ba...,75,24.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
8901,The Cuphead Show!,2021–,"Animation,Action,Adventure",NaN,"The 2 brothers, Cuphead and Mugman, stumble in...","Stars:Tru Valentino, Frank Tod...",NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
7786,Virgin River,2019–,"Drama,Romance",7.6,The town attends the annual picnic where resid...,Director:Gail Harvey| Stars:Alexandra ...,332,43.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
3202,Zeit der Geheimnisse,2019,Drama,6.5,A Christmas reunion becomes a gateway to the p...,"Stars:Corinna Harfouch, Christ...",986,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0

## Missing Data

In [49]:
columns_to_check = ['ONE-LINE', 'MOVIES', 'RATING', 'VOTES', 
                    'RunTime', 'Gross', 'TYPE', 'YEAR_FROM', 'YEAR_TO','GENRE']

missing_df = df[columns_to_check].isnull().sum().to_frame()
missing_df = missing_df.rename(columns={0: 'Missing Count'})
missing_df['missing_percentage'] = (missing_df['Missing Count'] / len(df)) * 100 #shape[0]
missing_df

           Missing Count  missing_percentage
ONE-LINE            1265           12.651265
MOVIES                 0            0.000000
RATING              1820           18.201820
VOTES               1820           18.201820
RunTime                0            0.000000
Gross               9539           95.399540
TYPE                   0            0.000000
YEAR_FROM            644            6.440644
YEAR_TO              644            6.440644
GENRE                 80            0.800080

YEAR_TO

In [32]:
df['YEAR_TO'].dtypes

In [33]:
#Take the current year
current_year = pd.Timestamp.now().year

df["YEAR_TO"] = np.where(
    df["YEAR_FROM"].notna() & df["YEAR_TO"].isna(),
    current_year,
    df["YEAR_TO"]
)

In [34]:
missing_df = df[columns_to_check].isnull().sum().to_frame()
missing_df

              0
ONE-LINE   1265
MOVIES        0
RATING     1820
VOTES      1820
RunTime    2958
Gross      9539
TYPE          0
YEAR_FROM   644
YEAR_TO     644

Run-Time

In [35]:
df["RunTime"].describe()

count    7041.000000
mean       68.688539
std        47.258056
min         1.000000
25%        36.000000
50%        60.000000
75%        95.000000
max       853.000000
Name: RunTime, dtype: float64

In [36]:
df[df['RunTime'] >= 600]

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,Director_Àlex Pastor,Director_Álex de la Iglesia,Director_Álvaro Brechner,Director_Álvaro Fernández Armero,Director_Álvaro Longoria,Director_Ángel Gómez Hernández,Director_Ángeles Reiné,Director_Åke Sandgren,Director_Óscar Pedraza,Director_Ömer Ugur
1081,Soupçons,2004–2018,"Documentary,Crime,Drama",7.9,The high-profile murder trial of American nove...,"Stars:Michael Peterson, David ...","20,200",629.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
1902,El tiempo entre costuras,2013–2014,"Adventure,Drama,History",8.3,Sira Quiroga is a young Spanish dressmaker eng...,"Stars:Adriana Ugarte, Mari Car...","3,876",853.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0

In [37]:
df[df["RunTime"].isna()].sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,Director_Àlex Pastor,Director_Álex de la Iglesia,Director_Álvaro Brechner,Director_Álvaro Fernández Armero,Director_Álvaro Longoria,Director_Ángel Gómez Hernández,Director_Ángeles Reiné,Director_Åke Sandgren,Director_Óscar Pedraza,Director_Ömer Ugur
7807,Explained,2018–,Documentary,7.3,"In pop culture, pirates are often depicted as ...","Stars:Natasha Lyonne, Lauren B...",231,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
4102,Doble Kara,2015–2017,"Comedy,Crime,Drama",9.1,NaN,"Stars:Mylene Dizon, Julia Mont...",12,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
7058,The Expanding Universe of Ashley Garcia,2020,Comedy,8.1,Go to Ashley indulges in glitz and glam when s...,Director:Jeff Melman| Stars:Paulina Ch...,30,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
7496,Mighty Little Bheem,2019–,"Animation,Short,Adventure",NaN,NaN,"Directors:Rajiv Chilaka, Krishna Mohan Chi...",NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
3087,Historia de un Crimen: La Busqueda,2020,Crime,5.5,Based on a true story about the disappearance ...,"Stars:Dario Yazbek Bernal, Dia...",561,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
5997,Untitled Asterix Project,NaN,Animation,NaN,NaN,,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
8731,Kipo and the Age of Wonderbeasts,2020,"Animation,Action,Adventure",8.0,"Hoping to tap her inner strength, Kipo hitches...",Director:Bridget Underwood| Stars:Kare...,114,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
6898,Brigada Costa del Sol,2019,"Action,Adventure,Drama",7.5,NaN,Director:Norberto López Amado| Stars:H...,21,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
5650,Meet the Voxels,NaN,NaN,NaN,The life of a family of video game characters.,"Stars:Micah Abbey, Ben Begley,...",NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
9923,Ginny & Georgia,2021–,"Comedy,Drama",NaN,NaN,Director:Anya Adams| Stars:Brianne How...,NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0

In [38]:
df["RunTime"][df["TYPE"] == "Series"].describe()

count    2876.000000
mean       39.269471
std        29.580547
min         1.000000
25%        24.000000
50%        38.000000
75%        47.000000
max       853.000000
Name: RunTime, dtype: float64

In [39]:
df["RunTime"][df["TYPE"] == "Movie"].describe()

count    4165.000000
mean       89.002881
std        46.488210
min         1.000000
25%        63.000000
50%        90.000000
75%       105.000000
max       573.000000
Name: RunTime, dtype: float64

In [40]:
movie_mean_runtime = df.loc[df["TYPE"] == "Movie", "RunTime"].mean()
df.loc[(df["TYPE"] == "Movie")&(df["RunTime"].isna()), "RunTime"] = movie_mean_runtime

In [41]:
movie_mean_runtime

np.float64(89.00288115246099)

In [42]:
df["RunTime"][df["TYPE"] == "Movie"].isna().sum()

np.int64(0)

In [43]:
series_mean_runtime = df.loc[df["TYPE"] == "Series", "RunTime"].mean()
series_mean_runtime

np.float64(39.26947148817803)

In [44]:
df.loc[(df["TYPE"] == "Series")&(df["RunTime"].isna()), "RunTime"] = series_mean_runtime

In [45]:
df["RunTime"][df["TYPE"] == "Series"].isna().sum()

np.int64(0)

In [48]:
df["VOTES"].dtype