Movie Feature Engineering

In [110]:
import pandas as pd
import numpy as np
import re
from tqdm.notebook import tqdm

In [111]:
tqdm.pandas()

In [112]:
df = pd.read_csv("../data/movies.csv")
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN

In [113]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MOVIES    9999 non-null   str
 1   YEAR      9355 non-null   str
 2   GENRE     9919 non-null   str
 3   RATING    8179 non-null   float64
 4   ONE-LINE  9999 non-null   str
 5   STARS     9999 non-null   str
 6   VOTES     8179 non-null   str
 7   RunTime   7041 non-null   float64
 8   Gross     460 non-null    str
dtypes: float64(2), str(7)
memory usage: 703.2 KB

Data Cleaning

Year

In [114]:
df['YEAR'] = df['YEAR'].str.replace('(','',regex=False)
df['YEAR'] = df['YEAR'].str.replace(')','',regex=False)
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,2021–,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,2010–2022,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,2013–,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN

In [115]:
df['TYPE'] = np.where(df['YEAR'].str.contains('–'), 'Series', 'Movie')
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE
0,Blood Red Sky,2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN,Movie
1,Masters of the Universe: Revelation,2021–,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN,Series
2,The Walking Dead,2010–2022,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN,Series
3,Rick and Morty,2013–,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN,Series
4,Army of Thieves,2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN,Movie

In [116]:
df['YEAR_FROM'] = np.nan
df['YEAR_TO'] = np.nan

df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
0,Blood Red Sky,2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN,Movie,NaN,NaN
1,Masters of the Universe: Revelation,2021–,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN,Series,NaN,NaN
2,The Walking Dead,2010–2022,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN,Series,NaN,NaN
3,Rick and Morty,2013–,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN,Series,NaN,NaN
4,Army of Thieves,2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN,Movie,NaN,NaN

In [117]:
df.sample(15)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
1251,Love & Anarchy,2020–,"\nComedy, Drama, Romance",7.4,"\nSofie, a career driven consultant and marrie...","\n \n Stars:\nIda Engvoll, \nBjö...","6,788",30.0,NaN,Series,NaN,NaN
8739,Kipo and the Age of Wonderbeasts,2020,"\nAnimation, Action, Adventure",8.9,"\nWith a little help from friends, Kipo breaks...","\n Directors:\nYoung Ki Yoon, \nMichael Cha...",124,NaN,NaN,Movie,NaN,NaN
8719,Power Rangers Beast Morphers,2019–2020,"\nAction, Adventure, Drama",7.8,\nNate and Steel accidentally swap bodies.,\n Director:\nOliver Driver\n| \n Stars:...,21,NaN,NaN,Series,NaN,NaN
8011,Undercover,2019–,"\nCrime, Drama, Thriller",7.2,\nJean-Pierre agrees to deliver weapons in exc...,\n Director:\nCecilia Verheyden\n| \n St...,241,49.0,NaN,Series,NaN,NaN
3015,It's Bruno!,2019–,\nComedy,7.5,\nAn old-school Brooklyn native devotes his da...,"\n \n Stars:\nSolvan Naim, \nBru...","2,662",15.0,NaN,Series,NaN,NaN
9715,Jiok,2021–,"\nDrama, Fantasy, Horror",NaN,\nAdd a Plot\n,\n Director:\nSang-ho Yeon\n| \n Stars:\...,NaN,NaN,NaN,Series,NaN,NaN
6478,Avatar: The Last Airbender,2005–2008,"\nAnimation, Action, Adventure",7.8,"\nAang, Katara, and Sokka have their friendshi...",\n Director:\nDave Filoni\n| \n Stars:\n...,"3,164",25.0,NaN,Series,NaN,NaN
4535,Miranda Sings Live... Your Welcome,2019,\nComedy,5.5,\nViral video star Miranda Sings and her real-...,\n Director:\nMarcus Raboy\n| \n Stars:\...,395,61.0,NaN,Movie,NaN,NaN
8903,The Rain,2018–2020,"\nDrama, Sci-Fi, Thriller",6.4,\nSimone's group approaches a camp of young su...,\n Director:\nKaspar Munk\n| \n Stars:\n...,313,NaN,NaN,Series,NaN,NaN
8136,Kalifat,2020–,"\nCrime, Drama, Thriller",7.6,"\nAs Ibbe lures Kerima, Sulle and Miryam into ...",\n Director:\nGoran Kapetanovic\n| \n St...,315,47.0,NaN,Series,NaN,NaN
6898,Brigada Costa del Sol,2019,"\nAction, Adventure, Drama",7.5,\nAdd a Plot\n,\n Director:\nNorberto López Amado\n| \n ...,21,NaN,NaN,Movie,NaN,NaN
4301,Hollywood & Wine,2011 Video,\nComedy,3.5,\nA struggling actress agrees to be an acting ...,"\n Directors:\nMatt Berman, \nKevin P. Farl...",394,95.0,NaN,Movie,NaN,NaN
2804,End of the Road,II,\nThriller,NaN,"\nA recently widowed Brenda, drives her family...",\n Director:\nMillicent Shelton\n| \n St...,NaN,NaN,NaN,Movie,NaN,NaN
5974,El-Harami wa el-Abit,2013,"\nComedy, Drama",5.1,\nA drama that discuss some of the issues and ...,\n Director:\nMohammed Moustafa\n| \n St...,262,90.0,NaN,Movie,NaN,NaN
3971,Maktub,2017,"\nComedy, Drama",7.3,\nThe biggest Israeli blockbuster since 1986 ....,\n Director:\nOded Raz\n| \n Stars:\nGuy...,"2,004",100.0,NaN,Movie,NaN,NaN

In [118]:
def extract_from(x):
    if pd.isna(x):
        return np.nan
    
    year_to_return = None

    year = str(x)
    if '–' not in year:
        year_to_return = year
    else:
        # 2010-2015 -> [2010, 2015]
        # 2010- -> [2010,]
        years = year.split('–')
        year_to_return = years[0]

    year_to_return = re.sub('[^0-9]', '', year_to_return)

    return year_to_return


def extract_to(x):
    if pd.isna(x):
        return np.nan
    
    year_to_return = None

    year = str(x)
    if '–' not in year:
        year_to_return = re.sub('[^0-9]', '', year)
        return year_to_return
    else:
        years = year.split('–')
        year_to_return = re.sub('[^0-9]', '', years[1])
        if len(year_to_return) == 0:
            return np.nan
        else:
            return year_to_return
    

df['YEAR_FROM'] = df['YEAR'].progress_apply(extract_from)
df['YEAR_TO'] = df['YEAR'].progress_apply(extract_to)

  0%|          | 0/9999 [00:00<?, ?it/s]

  0%|          | 0/9999 [00:00<?, ?it/s]

In [119]:
df.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
6087,Felipe Neto: Minha Vida Não Faz Sentido,2017 TV Special,"\nDocumentary, Comedy",4.1,\nYouTube sensation Felipe Neto brings the sto...,\n Director:\nDiego Pignataro\n| \n Star...,233,87.0,NaN,Movie,2017,2017
8066,Blood & Water,2020–,"\nDrama, Mystery",7.5,\nFiks faces backlash while campaigning for He...,\n Director:\nTravis Taute\n| \n Stars:\...,63,50.0,NaN,Series,2020,NaN
7376,She-Ra and the Princesses of Power,2018–2020,"\nAnimation, Action, Adventure",8.3,\nForce captain Adora wakes up in the Fright Z...,"\n Directors:\nRoy Burdine, \nMandy Clotwor...",999,24.0,NaN,Series,2018,2020
3059,Ruby the Hero Dog,2022,\nDrama,NaN,\nRuby had an awful lot of energy. Her origina...,\n Director:\nKatt Shea\n| \n Stars:\nGr...,NaN,NaN,NaN,Movie,2022,2022
3169,Once Again,2020–,"\nComedy, Drama, Romance",8.5,"\n""Once Again"" is a story about love and famil...","\n \n Stars:\nLee Min-Jung, \nHo...",178,35.0,NaN,Series,2020,NaN
5296,Franco Escamilla: Por la anécdota,2018 TV Special,\nComedy,7.0,\nAdd a Plot\n,\n Director:\nUlises Valencia\n| \n Star...,270,66.0,NaN,Movie,2018,2018
3582,#AnneFrank - Parallel Stories,2019,"\nDrama, History",6.5,\nIt is based on five women who did survive th...,"\n Directors:\nSabina Fedeli, \nAnna Migott...","1,296",92.0,NaN,Movie,2019,2019
3325,Splatter,2009–,\nHorror,3.2,\nAfter self-righteous rock star Jonny Splatte...,"\n \n Stars:\nCorey Feldman, \nM...",518,29.0,NaN,Series,2009,NaN
9734,Centaurworld,2021–,"\nAnimation, Adventure, Comedy",NaN,\nAdd a Plot\n,"\n \n Stars:\nParvesh Cheena, \n...",NaN,NaN,NaN,Series,2021,NaN
1740,Jui kuen II,1994,"\nAction, Comedy",7.6,\nA young martial artist is caught between res...,"\n Directors:\nChia-Liang Liu, \nJackie Cha...","44,060",102.0,$11.55M,Movie,1994,1994

Genre

In [120]:
df['GENRE'] = df['GENRE'].str.replace(' ', '', regex=False)
df['GENRE'] = df['GENRE'].str.replace('\n', '', regex=False)
df.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
9853,Kus uçusu,NaN,Comedy,NaN,\nAdd a Plot\n,\n Director:\nDeniz Yorulmazer\n| \n Sta...,NaN,NaN,NaN,Movie,NaN,NaN
8777,Colin in Black & White,2021–,"Biography,Drama,Sport",NaN,\nAdd a Plot\n,"\n \n Stars:\nAnna McKitrick, \n...",NaN,NaN,NaN,Series,2021,NaN
3363,We Baby Bears,2022–,"Animation,Adventure,Comedy",NaN,"\nThe bear siblings, Grizz, Panda and Ice Bear...",\n,NaN,NaN,NaN,Series,2022,NaN
8959,The Queen's Gambit,2020,Drama,9.3,\nA visit from an old friend forces Beth to re...,\n Director:\nScott Frank\n| \n Stars:\n...,"10,355",68.0,NaN,Movie,2020,2020
9856,Surviving Summer,2022–,Drama,NaN,\nAdd a Plot\n,\n Director:\nBen Chessell\n| \n Stars:\...,NaN,NaN,NaN,Series,2022,NaN
8340,Hyena,2020–,"Drama,Romance",8.2,\nAdd a Plot\n,\n Director:\nTae You Chang\n| \n Stars:...,11,NaN,NaN,Series,2020,NaN
5935,Virunga: Gorillas in Peril,2015 TV Movie,Documentary,6.2,\nA behind the scenes look at the Academy Awar...,\n Director:\nLisa Kors\n| \n Stars:\nSo...,28,28.0,NaN,Movie,2015,2015
6372,My First Day,2001,"Short,Family",NaN,\nBuddy Bear is afraid of attending his first ...,\n Director:\nJohn P. Aguirre\n| \n Star...,NaN,30.0,NaN,Movie,2001,2001
4067,Eric Andre: Legalize Everything,2020 TV Special,Comedy,6.2,\nEric Andre takes the stage in New Orleans an...,\n Director:\nEric Notarnicola\n| \n Sta...,"2,246",51.0,NaN,Movie,2020,2020
7531,The Irregulars,2021,"Crime,Drama,Fantasy",6.4,"\nAs Jessie's nightmares grow worse, Bea accep...",\n Director:\nJohnny Allan\n| \n Stars:\...,670,58.0,NaN,Movie,2021,2021

In [122]:
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
0,Blood Red Sky,2021,"Action,Horror,Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN,Movie,2021,2021
1,Masters of the Universe: Revelation,2021–,"Animation,Action,Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN,Series,2021,NaN
2,The Walking Dead,2010–2022,"Drama,Horror,Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN,Series,2010,2022
3,Rick and Morty,2013–,"Animation,Adventure,Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN,Series,2013,NaN
4,Army of Thieves,2021,"Action,Crime,Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN,Movie,2021,2021

In [121]:
df_dummy = df['GENRE'].str.get_dummies(sep=',')
df_dummy = df_dummy.add_prefix('GENRE_')
df_dummy.head()

,GENRE_Action,GENRE_Adventure,GENRE_Animation,GENRE_Biography,GENRE_Comedy,GENRE_Crime,GENRE_Documentary,GENRE_Drama,GENRE_Family,GENRE_Fantasy,...,GENRE_News,GENRE_Reality-TV,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [123]:
df_dummy.shape

(9999, 27)

In [124]:
df.shape

(9999, 12)

In [125]:
#Join/Merge the dummy dataframe with the original dataframe
#df = df.join(df_dummy)
df = df.merge(df_dummy, left_index=True, right_index=True)
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,GENRE_News,GENRE_Reality-TV,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western
0,Blood Red Sky,2021,"Action,Horror,Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN,Movie,...,0,0,0,0,0,0,0,1,0,0
1,Masters of the Universe: Revelation,2021–,"Animation,Action,Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
2,The Walking Dead,2010–2022,"Drama,Horror,Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN,Series,...,0,0,0,0,0,0,0,1,0,0
3,Rick and Morty,2013–,"Animation,Adventure,Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
4,Army of Thieves,2021,"Action,Crime,Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0