Movie Feature Engineering

In [1]:
import pandas as pd
import numpy as np
import re
from tqdm.notebook import tqdm

In [2]:
tqdm.pandas()

In [3]:
df = pd.read_csv("../data/movies.csv")
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   MOVIES    9999 non-null   str
 1   YEAR      9355 non-null   str
 2   GENRE     9919 non-null   str
 3   RATING    8179 non-null   float64
 4   ONE-LINE  9999 non-null   str
 5   STARS     9999 non-null   str
 6   VOTES     8179 non-null   str
 7   RunTime   7041 non-null   float64
 8   Gross     460 non-null    str
dtypes: float64(2), str(7)
memory usage: 703.2 KB

## Data Cleaning

Year

In [5]:
df['YEAR'] = df['YEAR'].str.replace('(','',regex=False)
df['YEAR'] = df['YEAR'].str.replace(')','',regex=False)
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,2021–,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,2010–2022,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,2013–,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN

In [6]:
df['TYPE'] = np.where(df['YEAR'].str.contains('–'), 'Series', 'Movie')
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE
0,Blood Red Sky,2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN,Movie
1,Masters of the Universe: Revelation,2021–,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN,Series
2,The Walking Dead,2010–2022,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN,Series
3,Rick and Morty,2013–,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN,Series
4,Army of Thieves,2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN,Movie

In [7]:
df['YEAR_FROM'] = np.nan
df['YEAR_TO'] = np.nan

df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
0,Blood Red Sky,2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN,Movie,NaN,NaN
1,Masters of the Universe: Revelation,2021–,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN,Series,NaN,NaN
2,The Walking Dead,2010–2022,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN,Series,NaN,NaN
3,Rick and Morty,2013–,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN,Series,NaN,NaN
4,Army of Thieves,2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN,Movie,NaN,NaN

In [8]:
df.sample(15)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
416,Vanquish,2021,"\nAction, Crime, Thriller",2.7,"\nA mother, Victoria, is trying to put her dar...",\n Director:\nGeorge Gallo\n| \n Stars:\...,"3,010",94.0,NaN,Movie,NaN,NaN
6789,Baby,2018–2020,\nDrama,7.9,"\nLudo gets infuriating news, Chiara and her p...",\n Director:\nAndrea De Sica\n| \n Stars...,117,41.0,NaN,Series,NaN,NaN
2650,Naesungjukin Boseu,2017,"\nComedy, Drama, Romance",7.3,\nEun Hwan-Ki is the CEO of a public relation ...,"\n \n Stars:\nGong Seung-Yeon, \...","1,290",70.0,NaN,Movie,NaN,NaN
7906,Queen Sono,2020–2021,"\nAction, Crime, Drama",6.8,\nAdd a Plot\n,\n Director:\nKagiso Lediga\n| \n Stars:...,65,NaN,NaN,Series,NaN,NaN
5129,Ugly Duckling Series: Perfect Match,2015,"\nDrama, Romance",7.3,"\nJunita, nicknamed Junior, did plastic surger...",\n \n Stars:\nOnnicha Akkharasew...,39,50.0,NaN,Movie,NaN,NaN
4142,Skytten,2013,"\nCrime, Drama, Thriller",5.5,\nA reporter confronts the Danish foreign mini...,\n Director:\nAnnette K. Olesen\n| \n St...,"1,611",90.0,NaN,Movie,NaN,NaN
2047,A Shaun the Sheep Movie: Farmageddon,2019,"\nAnimation, Adventure, Comedy",6.8,\nWhen an alien with amazing powers crash-land...,"\n Directors:\nWill Becher, \nRichard Phela...","12,154",86.0,NaN,Movie,NaN,NaN
2770,"Strip Down, Rise Up",2021,\nDocumentary,5.2,\nAcademy Award Nominated director Michèle Oha...,\n Director:\nMichèle Ohayon\n| \n Stars...,530,112.0,NaN,Movie,NaN,NaN
385,There's Something About Mary,1998,"\nComedy, Romance",7.1,\nA man gets a chance to meet up with his drea...,"\n Directors:\nBobby Farrelly, \nPeter Farr...","298,729",119.0,$176.48M,Movie,NaN,NaN
7652,Hollywood,2020,\nDrama,8.1,\nDick and Ellen pitch Ace their slate. Raymon...,\n Director:\nJanet Mock\n| \n Stars:\nD...,"1,226",47.0,NaN,Movie,NaN,NaN
1378,1899,2022–,"\nDrama, History, Horror",NaN,\nMultinational immigrants traveling from the ...,"\n \n Stars:\nAneurin Barnard, \...",NaN,NaN,NaN,Series,NaN,NaN
4027,Free Rein: The Twelve Neighs of Christmas,2018 TV Movie,"\nAdventure, Comedy, Drama",6.5,\nWhile Bright Fields preps for its Mistletoe ...,\n Director:\nMarek Losey\n| \n Stars:\n...,"2,761",56.0,NaN,Movie,NaN,NaN
5756,Running Mates,2011,\nComedy,5.3,\nTwo best friends run against each other for ...,\n Director:\nThomas Michael\n| \n Stars...,108,90.0,NaN,Movie,NaN,NaN
3495,Treasures from the Wreck of the Unbelievable,2017,\nDocumentary,6.0,\nThe fake story of the art found beneath the ...,\n Director:\nSam Hobkinson\n| \n Stars:...,"1,442",90.0,NaN,Movie,NaN,NaN
7230,Space Force,2020–,\nComedy,7.0,\nGeneral Naird volunteers for Dr. Mallory's L...,\n Director:\nPaul King\n| \n Stars:\nSt...,"1,787",31.0,NaN,Series,NaN,NaN

In [9]:
def extract_from(x):
    if pd.isna(x):
        return np.nan
    
    year_to_return = None

    year = str(x)
    if '–' not in year:
        year_to_return = year
    else:
        # 2010-2015 -> [2010, 2015]
        # 2010- -> [2010,]
        years = year.split('–')
        year_to_return = years[0]

    year_to_return = re.sub('[^0-9]', '', year_to_return)

    return year_to_return


def extract_to(x):
    if pd.isna(x):
        return np.nan
    
    year_to_return = None

    year = str(x)
    if '–' not in year:
        year_to_return = re.sub('[^0-9]', '', year)
        return year_to_return
    else:
        years = year.split('–')
        year_to_return = re.sub('[^0-9]', '', years[1])
        if len(year_to_return) == 0:
            return np.nan
        else:
            return year_to_return
    

df['YEAR_FROM'] = df['YEAR'].progress_apply(extract_from)
df['YEAR_TO'] = df['YEAR'].progress_apply(extract_to)

  0%|          | 0/9999 [00:00<?, ?it/s]

  0%|          | 0/9999 [00:00<?, ?it/s]

In [10]:
df.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
7080,Lucifer,2016–2021,"\nCrime, Drama, Fantasy",8.2,\nLucifer toys with a murder victim while Chlo...,\n Director:\nEagle Egilsson\n| \n Stars...,"3,620",51.0,NaN,Series,2016,2021
1602,Love/Hate,2010–2014,"\nCrime, Drama",8.5,\nThe story of the organized crime scene of Du...,\n \n Stars:\nTom Vaughan-Lawlor...,"6,346",51.0,NaN,Series,2010,2014
7130,Pacific Rim,2021–,"\nAnimation, Action, Adventure",7.1,"\nWhile on foot, Taylor, Hayley and Boy encoun...","\n Directors:\nHiroki Hayashi, \nJae Hong K...",186,21.0,NaN,Series,2021,NaN
7075,Aseudal Yeondaegi,2019–,"\nAction, Drama, Fantasy",8.9,\nAdd a Plot\n,\n Director:\nWon Suk Kim\n| \n Stars:\n...,146,80.0,NaN,Series,2019,NaN
8681,Dexter,2006–2013,"\nCrime, Drama, Mystery",8.5,\nDexter hears the story of a husband who has ...,\n Director:\nMarcos Siega\n| \n Stars:\...,"3,619",49.0,NaN,Series,2006,2013
4943,One in a Billion,2016,\nDocumentary,6.7,\nIn a country of 1.2 billion people and in a ...,\n Director:\nRoman Gackowski\n| \n Star...,511,69.0,NaN,Movie,2016,2016
8518,Valeria,2020–,"\nComedy, Drama, Romance",7.8,\nAdd a Plot\n,\n Director:\nInma Torrente\n| \n Stars:...,65,NaN,NaN,Series,2020,NaN
542,Hush,I 2016,"\nHorror, Thriller",6.6,\nA deaf and mute writer who retreated into th...,\n Director:\nMike Flanagan\n| \n Stars:...,"112,354",82.0,NaN,Movie,2016,2016
4649,Côpusu pâtî,2015,\nHorror,4.7,"\nFacing goodbyes and graduation, Naomi Nakash...",\n Director:\nMasafumi Yamada\n| \n Star...,420,93.0,NaN,Movie,2015,2015
5897,Vaquero,2011,\nDrama,6.4,"\nThe story of Julián Lamar, an Argentine acto...",\n Director:\nJuan Minujín\n| \n Stars:\...,221,87.0,NaN,Movie,2011,2011

Genre

In [11]:
df['GENRE'] = df['GENRE'].str.replace(' ', '', regex=False)
df['GENRE'] = df['GENRE'].str.replace('\n', '', regex=False)
df.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
8292,Johnny Test,2005–,"Animation,Action,Adventure",5.9,"\nTrying to improve on human evolution, the gi...",\n Director:\nLarry Jacobs\n| \n Stars:\...,26,23.0,NaN,Series,2005,NaN
9585,Dota: Dragon's Blood,2021–,"Animation,Action,Adventure",8.6,\nAfter the goddess declared war on the unbeli...,"\n Directors:\nYu-Won Pang, \nEui Jeong Kim...",516,26.0,NaN,Series,2021,NaN
1854,Ask the StoryBots,2016–2019,"Animation,Adventure,Comedy",8.4,"\nBased on the award-winning educational apps,...","\n \n Stars:\nJudy Greer, \nErin...",750,24.0,NaN,Series,2016,2019
4784,Goli Soda 2,2018,"Action,Drama",7.2,\nThe story revolves around the lives of 3 you...,\n Director:\nVijay Milton\n| \n Stars:\...,762,128.0,NaN,Movie,2018,2018
2521,Super Wings!,2015–,"Animation,Adventure,Family",6.1,\nA jet plane named Jett travels the world del...,"\n \n Stars:\nLuca Padovan, \nHu...",287,15.0,NaN,Series,2015,NaN
9938,Master of None,2015–,"Comedy,Drama",5.7,\nA trip upstate leads to reflections on the p...,\n Director:\nAziz Ansari\n| \n Stars:\n...,658,31.0,NaN,Series,2015,NaN
4768,Kingdom of Us,2017,"Documentary,Drama",7.1,\nA father's suicide sends a family of eight o...,\n Director:\nLucy Cohen\n| \n Stars:\nJ...,828,109.0,NaN,Movie,2017,2017
812,Sseulsseulhago Chalranhashin: Dokkaebi,2016–2017,"Comedy,Drama,Fantasy",8.6,\nIn his quest for a bride to break his immort...,"\n \n Stars:\nGong Yoo, \nKim Go...","14,034",60.0,NaN,Series,2016,2017
7716,The Last Kingdom,2015–,"Action,Drama,History",9.4,\nAethelflaed and Uhtred ally with the Welsh k...,\n Director:\nSarah O'Gorman\n| \n Stars...,"2,105",51.0,NaN,Series,2015,NaN
4533,Sunny Bunnies,2015–,"Animation,Family",6.8,\nThe series focuses on 5 colored bunnies (Tur...,"\n \n Stars:\nDmitri Davidovich,...",74,NaN,NaN,Series,2015,NaN

In [12]:
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,YEAR_FROM,YEAR_TO
0,Blood Red Sky,2021,"Action,Horror,Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN,Movie,2021,2021
1,Masters of the Universe: Revelation,2021–,"Animation,Action,Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN,Series,2021,NaN
2,The Walking Dead,2010–2022,"Drama,Horror,Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN,Series,2010,2022
3,Rick and Morty,2013–,"Animation,Adventure,Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN,Series,2013,NaN
4,Army of Thieves,2021,"Action,Crime,Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN,Movie,2021,2021

In [13]:
df_dummy = df['GENRE'].str.get_dummies(sep=',')
df_dummy = df_dummy.add_prefix('GENRE_')
df_dummy.head()

,GENRE_Action,GENRE_Adventure,GENRE_Animation,GENRE_Biography,GENRE_Comedy,GENRE_Crime,GENRE_Documentary,GENRE_Drama,GENRE_Family,GENRE_Fantasy,...,GENRE_News,GENRE_Reality-TV,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
df_dummy.shape

(9999, 27)

In [15]:
df.shape

(9999, 12)

In [16]:
#Join/Merge the dummy dataframe with the original dataframe
#df = df.join(df_dummy)
df = df.merge(df_dummy, left_index=True, right_index=True)
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,GENRE_News,GENRE_Reality-TV,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western
0,Blood Red Sky,2021,"Action,Horror,Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN,Movie,...,0,0,0,0,0,0,0,1,0,0
1,Masters of the Universe: Revelation,2021–,"Animation,Action,Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
2,The Walking Dead,2010–2022,"Drama,Horror,Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN,Series,...,0,0,0,0,0,0,0,1,0,0
3,Rick and Morty,2013–,"Animation,Adventure,Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
4,Army of Thieves,2021,"Action,Crime,Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0

Stars

In [17]:
df.sample(15)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,GENRE_News,GENRE_Reality-TV,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western
567,Girl From Nowhere,2018–,"Crime,Drama,Fantasy",7.7,"\nA mysterious, clever girl named Nanno transf...","\n \n Stars:\nChicha Amatayakul,...","2,703",45.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
373,Halston,2021,"Biography,Drama",7.5,"\nThe story of a man who leverages his single,...","\n \n Stars:\nEwan McGregor, \nR...","10,460",240.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
6450,The Bastard Sings the Sweetest Song,2012,"Documentary,Drama,Family",7.0,"\nIn Georgetown, Guyana, Muscle and his mother...",\n Director:\nChristy Garland\n,27,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
5028,Jimmy: Ahomitaina honma no hanashi,2018–,Comedy,6.8,"\nIn the 1980s, a simple-minded fool named Hid...","\n \n Stars:\nAkiyoshi Nakao, \n...",64,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
8934,Glitch Techs,2020–,"Animation,Action,Adventure",7.5,\nWhile gathered together to play a deduction ...,\n Director:\nHyun Joo Song\n| \n Stars:...,42,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
3980,Alice Júnior,2019,"Animation,Comedy,Drama",7.0,\nThe first kiss of a transgender teenager.,\n Director:\nGil Baroni\n| \n Stars:\nA...,448,87.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
846,Crashing,2016,Comedy,7.7,\nA comedy series following the lives of six 2...,\n \n Stars:\nPhoebe Waller-Brid...,"16,276",30.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
558,Cars 3,2017,"Animation,Adventure,Comedy",6.7,\nLightning McQueen sets out to prove to a new...,\n Director:\nBrian Fee\n| \n Stars:\nOw...,"83,135",102.0,$152.90M,Movie,...,0,0,0,0,0,0,0,0,0,0
8314,On the Verge,2021–,Comedy,NaN,\nAdd a Plot\n,\n Director:\nJulie Delpy\n| \n Stars:\n...,NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
7668,Toy Boy,2019,"Crime,Drama,Thriller",7.4,\nAfter Jairo loses the pen-drive with Andrea'...,\n Director:\nIñaki Mercero\n| \n Stars:...,113,NaN,NaN,Movie,...,0,0,0,0,0,0,0,1,0,0
7554,Super Monsters,2017–,"Animation,Adventure,Comedy",5.8,\nThe Super Monsters share their Halloween tra...,"\n \n Stars:\nMaria J. Cruz, \nG...",46,24.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
1060,Cam,2018,"Drama,Horror,Mystery",5.9,"\nAlice, an ambitious camgirl, wakes up one da...",\n Director:\nDaniel Goldhaber\n| \n Sta...,"28,739",94.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
865,Snabba Cash,2021–,"Action,Crime,Drama",7.6,\nThe entrepreneurial jet set as well as the c...,"\n \n Stars:\nEvin Ahmad, \nAlex...","6,551",52.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
5974,El-Harami wa el-Abit,2013,"Comedy,Drama",5.1,\nA drama that discuss some of the issues and ...,\n Director:\nMohammed Moustafa\n| \n St...,262,90.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
6468,Jandino: Whatever it Takes,2016 TV Special,Comedy,4.6,\nJandino Asporaat riffs on the challenges of ...,"\n \n Stars:\nJandino Asporaat, ...",28,95.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0

In [18]:
df['STARS'] = df['STARS'].str.replace('\n', '', regex=False)
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,GENRE_News,GENRE_Reality-TV,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western
0,Blood Red Sky,2021,"Action,Horror,Thriller",6.1,\nA woman with a mysterious illness is forced ...,Director:Peter Thorwarth| Stars:Peri B...,"21,062",121.0,NaN,Movie,...,0,0,0,0,0,0,0,1,0,0
1,Masters of the Universe: Revelation,2021–,"Animation,Action,Adventure",5.0,\nThe war for Eternia begins again in what may...,"Stars:Chris Wood, Sarah Michel...","17,870",25.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
2,The Walking Dead,2010–2022,"Drama,Horror,Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"Stars:Andrew Lincoln, Norman R...","885,805",44.0,NaN,Series,...,0,0,0,0,0,0,0,1,0,0
3,Rick and Morty,2013–,"Animation,Adventure,Comedy",9.2,\nAn animated series that follows the exploits...,"Stars:Justin Roiland, Chris Pa...","414,849",23.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
4,Army of Thieves,2021,"Action,Crime,Horror",NaN,"\nA prequel, set before the events of Army of ...",Director:Matthias Schweighöfer| Stars:...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0

In [19]:
df["Directors"] = None
df["Actors"] = None

def extract_directors(x):
    if "Director" in x:
        stars = x.split("|")
        if "Director" in stars[0]:
            return stars[0]
        else:
            return stars[1]
    else:
        return np.nan

def extract_actors(x):
    if "Star" in x:
        stars = x.split("|")
        if "Star" in stars[0]:
            return stars[0]
        else:
            return stars[1]
    else:
        return np.nan
    
df["Directors"] = df["STARS"].progress_apply(extract_directors)
df["Actors"] = df["STARS"].progress_apply(extract_actors)

df.head()

  0%|          | 0/9999 [00:00<?, ?it/s]

  0%|          | 0/9999 [00:00<?, ?it/s]

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western,Directors,Actors
0,Blood Red Sky,2021,"Action,Horror,Thriller",6.1,\nA woman with a mysterious illness is forced ...,Director:Peter Thorwarth| Stars:Peri B...,"21,062",121.0,NaN,Movie,...,0,0,0,0,0,1,0,0,Director:Peter Thorwarth,"Stars:Peri Baumeister, Carl Anton Koch, A..."
1,Masters of the Universe: Revelation,2021–,"Animation,Action,Adventure",5.0,\nThe war for Eternia begins again in what may...,"Stars:Chris Wood, Sarah Michel...","17,870",25.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Stars:Chris Wood, Sarah Michel..."
2,The Walking Dead,2010–2022,"Drama,Horror,Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"Stars:Andrew Lincoln, Norman R...","885,805",44.0,NaN,Series,...,0,0,0,0,0,1,0,0,NaN,"Stars:Andrew Lincoln, Norman R..."
3,Rick and Morty,2013–,"Animation,Adventure,Comedy",9.2,\nAn animated series that follows the exploits...,"Stars:Justin Roiland, Chris Pa...","414,849",23.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Stars:Justin Roiland, Chris Pa..."
4,Army of Thieves,2021,"Action,Crime,Horror",NaN,"\nA prequel, set before the events of Army of ...",Director:Matthias Schweighöfer| Stars:...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,Director:Matthias Schweighöfer,"Stars:Matthias Schweighöfer, Nathalie Emm..."

In [20]:
df.sample(15)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western,Directors,Actors
1724,Untitled Sandra Bullock/Nora Fingscheidt Project,2021,Drama,NaN,\nA woman is released from prison after servin...,Director:Nora Fingscheidt| Stars:Sandr...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,Director:Nora Fingscheidt,"Stars:Sandra Bullock, Vincent D'Onofrio, ..."
1655,Zui quan,1978,"Action,Comedy",7.5,\nWong Fei-Hung (Jackie Chan) is a mischievous...,Director:Woo-Ping Yuen| Stars:Jackie C...,"38,076",111.0,NaN,Movie,...,0,0,0,0,0,0,0,0,Director:Woo-Ping Yuen,"Stars:Jackie Chan, Siu-Tin Yuen, Jang-Lee..."
4779,Jo Koy: Comin' in Hot,2019 TV Special,Comedy,7.3,\nComedian Jo Koy takes center stage in Hawaii...,Director:Shannon Hartman| Star:Jo Koy,839,60.0,NaN,Movie,...,0,0,0,0,0,0,0,0,Director:Shannon Hartman,Star:Jo Koy
1570,Naissance des pieuvres,2007,"Drama,Romance",6.7,\nAfter meeting at a local pool over their sum...,Director:Céline Sciamma| Stars:Pauline...,"10,813",85.0,$0.08M,Movie,...,1,0,0,0,0,0,0,0,Director:Céline Sciamma,"Stars:Pauline Acquart, Louise Blachère, A..."
1778,Mandela,2021,"Comedy,Drama",8.5,\nA local barber's fate turns overnight when h...,Director:Madonne Ashwin| Stars:Yogi Ba...,"4,826",140.0,NaN,Movie,...,0,0,0,0,0,0,0,0,Director:Madonne Ashwin,"Stars:Yogi Babu, Sheela Rajkumar, Sangili..."
7861,She-Ra and the Princesses of Power,2018–2020,"Animation,Action,Adventure",9.3,\nRazz confuses the past and the present and h...,Director:Mandy Clotworthy| Stars:Aimee...,"1,067",24.0,NaN,Series,...,0,0,0,0,0,0,0,0,Director:Mandy Clotworthy,"Stars:Aimee Carrero, Marcus Scribner, Zeh..."
5562,Larry the Cable Guy: Remain Seated,2020 TV Special,Comedy,6.7,\nLarry the Cable Guy is back to Git R Done. R...,Director:Brian Volk-Weiss| Star:Larry ...,219,67.0,NaN,Movie,...,0,0,0,0,0,0,0,0,Director:Brian Volk-Weiss,Star:Larry the Cable Guy
270,Below Deck Mediterranean,2016–,Reality-TV,7.3,\nA reality show following the crew of the Ion...,"Stars:Hannah Ferrier, Sandy Ya...","1,327",43.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Stars:Hannah Ferrier, Sandy Ya..."
1351,The Week Of,2018,Comedy,5.2,\nTwo fathers with opposing personalities come...,Director:Robert Smigel| Stars:Adam San...,"20,005",116.0,NaN,Movie,...,0,0,0,0,0,0,0,0,Director:Robert Smigel,"Stars:Adam Sandler, Chris Rock, Steve Bus..."
3592,Trailer Park Boys: Don't Legalize It,2014,"Comedy,Crime,Drama",7.3,"\nAfter his latest money-making plan fails, Ju...",Director:Mike Clattenburg| Stars:John ...,"4,562",95.0,NaN,Movie,...,0,0,0,0,0,0,0,0,Director:Mike Clattenburg,"Stars:John Paul Tremblay, Robb Wells, Mik..."
3028,Iliza Shlesinger: War Paint,2013 TV Special,Comedy,6.7,\nHer innocent good looks are just a cover for...,Director:Jay Chapman| Star:Iliza Shles...,"1,924",75.0,NaN,Movie,...,0,0,0,0,0,0,0,0,Director:Jay Chapman,Star:Iliza Shlesinger
3247,Chomyeone Saranghamnida,2019–,"Comedy,Romance",7.4,"\nDo Min Ik is an intelligent, perfectionist m...","Stars:Ki-joo Jin, Kim Young-kw...",788,35.0,NaN,Series,...,1,0,0,0,0,0,0,0,NaN,"Stars:Ki-joo Jin, Kim Young-kw..."
9227,Dive Club,2021–,"Drama,Family,Mystery",NaN,\nDive Club discovers that Hayden's coin has s...,Director:Hayley MacFarlane| Stars:Miah...,NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,Director:Hayley MacFarlane,"Stars:Miah Madden, Georgia-May Davis, San..."
779,Conan the Barbarian,2011,"Action,Adventure,Fantasy",5.2,\nA vengeful barbarian warrior sets off to get...,Director:Marcus Nispel| Stars:Jason Mo...,"96,638",113.0,$21.30M,Movie,...,0,0,0,0,0,0,0,0,Director:Marcus Nispel,"Stars:Jason Momoa, Ron Perlman, Rose McGo..."
9158,50M2,2021–,"Comedy,Drama,Thriller",6.9,"\nWhile seeking answers about his parents, Sha...",Director:Selçuk Aydemir| Stars:Engin Ö...,148,51.0,NaN,Series,...,0,0,0,0,0,1,0,0,Director:Selçuk Aydemir,"Stars:Engin Öztürk, Kürsat Alniaçik, Ceng..."

In [21]:
df["Directors"] = df["Directors"].str.replace('Director:', '', regex=False)
df["Directors"] = df["Directors"].str.replace('Directors:', '', regex=False)
df["Actors"] = df["Actors"].str.replace('Star:', '', regex=False)
df["Actors"] = df["Actors"].str.replace('Stars:', '', regex=False)
df.head(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,GENRE_Romance,GENRE_Sci-Fi,GENRE_Short,GENRE_Sport,GENRE_Talk-Show,GENRE_Thriller,GENRE_War,GENRE_Western,Directors,Actors
0,Blood Red Sky,2021,"Action,Horror,Thriller",6.1,\nA woman with a mysterious illness is forced ...,Director:Peter Thorwarth| Stars:Peri B...,"21,062",121.0,NaN,Movie,...,0,0,0,0,0,1,0,0,Peter Thorwarth,"Peri Baumeister, Carl Anton Koch, Alexand..."
1,Masters of the Universe: Revelation,2021–,"Animation,Action,Adventure",5.0,\nThe war for Eternia begins again in what may...,"Stars:Chris Wood, Sarah Michel...","17,870",25.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Chris Wood, Sarah Michelle Gel..."
2,The Walking Dead,2010–2022,"Drama,Horror,Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"Stars:Andrew Lincoln, Norman R...","885,805",44.0,NaN,Series,...,0,0,0,0,0,1,0,0,NaN,"Andrew Lincoln, Norman Reedus,..."
3,Rick and Morty,2013–,"Animation,Adventure,Comedy",9.2,\nAn animated series that follows the exploits...,"Stars:Justin Roiland, Chris Pa...","414,849",23.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Justin Roiland, Chris Parnell,..."
4,Army of Thieves,2021,"Action,Crime,Horror",NaN,"\nA prequel, set before the events of Army of ...",Director:Matthias Schweighöfer| Stars:...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,Matthias Schweighöfer,"Matthias Schweighöfer, Nathalie Emmanuel,..."
5,Outer Banks,2020–,"Action,Crime,Drama",7.6,\nA group of teenagers from the wrong side of ...,"Stars:Chase Stokes, Madelyn Cl...","25,858",50.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Chase Stokes, Madelyn Cline, M..."
6,The Last Letter from Your Lover,2021,"Drama,Romance",6.8,\nA pair of interwoven stories set in the past...,Director:Augustine Frizzell| Stars:Sha...,"5,283",110.0,NaN,Movie,...,1,0,0,0,0,0,0,0,Augustine Frizzell,"Shailene Woodley, Joe Alwyn, Wendy Nottin..."
7,Dexter,2006–2013,"Crime,Drama,Mystery",8.6,"\nBy day, mild-mannered Dexter is a blood-spat...","Stars:Michael C. Hall, Jennife...","665,387",53.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Michael C. Hall, Jennifer Carp..."
8,Never Have I Ever,2020–,Comedy,7.9,\nThe complicated life of a modern-day first g...,"Stars:Maitreyi Ramakrishnan, P...","34,530",30.0,NaN,Series,...,0,0,0,0,0,0,0,0,NaN,"Maitreyi Ramakrishnan, Poorna ..."
9,Virgin River,2019–,"Drama,Romance",7.4,"\nSeeking a fresh start, nurse practitioner Me...","Stars:Alexandra Breckenridge, ...","27,279",44.0,NaN,Series,...,1,0,0,0,0,0,0,0,NaN,"Alexandra Breckenridge, Martin..."

Dummy on Actors

In [22]:
df["Actors"] = df["Actors"].str.replace(", ", ",", regex=False)
df["Actors"] = df["Actors"].str.strip()

df_dummy = df['Actors'].str.get_dummies(sep=',')
df_dummy = df_dummy.add_prefix('Actor_')
df_dummy.head()

,Actor_2 Chainz,Actor_2'Live Bre,Actor_2Mex,Actor_50 Cent,Actor_A Boogie wit da Hoodie,Actor_A.J. Baime,Actor_A.J. Daulerio,Actor_A.J. LoCascio,Actor_A.N.T.I.,Actor_AJ Bowen,...,Actor_Özge Borak,Actor_Özge Özpirinçci,Actor_Özgür Emre Yildirim,Actor_Özgür Ozan,Actor_Özkan Ugur,Actor_Özz Nûjen,Actor_Úrsula Corberó,Actor_Úrsula Pruneda,Actor_Ülkü Duru,Actor_Þorsteinn Bachmann
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
df_dummy.shape

(9999, 17325)

In [24]:
#merge/join the dummy dataframe with the original dataframe
df = df.merge(df_dummy, left_index=True, right_index=True)
df.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,Actor_Özge Borak,Actor_Özge Özpirinçci,Actor_Özgür Emre Yildirim,Actor_Özgür Ozan,Actor_Özkan Ugur,Actor_Özz Nûjen,Actor_Úrsula Corberó,Actor_Úrsula Pruneda,Actor_Ülkü Duru,Actor_Þorsteinn Bachmann
6111,A god in ruins,NaN,"Drama,Western",NaN,\na movie about a racist clan,,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
987,Goosebumps,1995–1998,"Family,Fantasy,Horror",7.7,\nA series of scary anthology stories based on...,"Stars:R.L. Stine, Kathryn Shor...","12,427",22.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
5196,Il diavolo e l'acquasanta,1983,Comedy,5.1,\nAdd a Plot\n,Director:Bruno Corbucci| Stars:Tomas M...,110,92.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
387,Binsenjo,2021–,"Comedy,Crime,Romance",8.5,"\nDuring a visit to his motherland, a Korean-I...","Stars:Song Joong-ki, Jeon Yeo-...","7,888",80.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
3051,Whitney,2018,"Documentary,Biography,Drama",7.3,\nAn in-depth look at the life and music of Wh...,Director:Kevin Macdonald| Stars:Whitne...,"7,004",120.0,$3.03M,Movie,...,0,0,0,0,0,0,0,0,0,0
6563,Bleach: Burîchi,2004–2012,"Animation,Action,Adventure",7.9,"\nRukia and Chad take on Shurîkâ, a vicious Ho...","Directors:Noriyuki Abe, Kazunori Mizuno| ...",261,24.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
3506,HaMossad: Sipur Kisuy,2017,Documentary,7.5,"\nFor years the Mossad, Israel's legendary for...","Stars:Ram Ben Barak, Gad Shimr...","1,056",60.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
7136,Bojwagwan,2019–,Drama,8.6,\nAdd a Plot\n,Director:Kwak Jung-Hwan| Stars:Jung-ja...,7,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
7196,The Protector,2018–2020,"Action,Fantasy,Sci-Fi",6.7,\nZeynep and Hakan race against time to find N...,Director:Umut Aral| Stars:Çagatay Ulus...,341,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
2636,Börü,2018,"Action,Thriller,War",8.2,\nTurkey in the spring of 2014. A time when th...,"Stars:Ahu Türkpençe, Serkan Ça...","6,607",80.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0

Dummy on Director

In [25]:
df["Directors"] = df["Directors"].str.replace(", ", ",", regex=False)
df["Directors"] = df["Directors"].str.strip()

df_dummy = df['Directors'].str.get_dummies(sep=',')
df_dummy = df_dummy.add_prefix('Director_')
df_dummy.head()

,Director_Aadish Keluskar,Director_Aaron Augenblick,Director_Aaron Burns,Director_Aaron Hann,Director_Aaron Lieber,Director_Aaron Long,Director_Aaron Moorhead,Director_Aaron Saidman,Director_Aaron Sorkin,Director_Aban Raza,...,Director_Àlex Pastor,Director_Álex de la Iglesia,Director_Álvaro Brechner,Director_Álvaro Fernández Armero,Director_Álvaro Longoria,Director_Ángel Gómez Hernández,Director_Ángeles Reiné,Director_Åke Sandgren,Director_Óscar Pedraza,Director_Ömer Ugur
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
#merge the dummy dataframe with the original dataframe
df = df.merge(df_dummy, left_index=True, right_index=True)
df.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,Director_Àlex Pastor,Director_Álex de la Iglesia,Director_Álvaro Brechner,Director_Álvaro Fernández Armero,Director_Álvaro Longoria,Director_Ángel Gómez Hernández,Director_Ángeles Reiné,Director_Åke Sandgren,Director_Óscar Pedraza,Director_Ömer Ugur
8529,Too Hot to Handle,2020–,"Game-Show,Reality-TV,Romance",5.0,\nRhonda and Sharron recap their night of roma...,"Stars:Bryce Hirschberg, Chloe ...",272,42.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
6045,2006 Independent Spirit Awards,2006 TV Special,NaN,6.6,\nAdd a Plot\n,Director:Chris Donovan| Stars:Sarah Si...,83,109.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
6408,Waxing Gibbous,2001,Drama,5.6,\nAdd a Plot\n,Director:Jim Fogarty| Stars:Janet Kay ...,18,97.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
5779,Mexico Diseña,2016–,"Game-Show,Reality-TV",5.6,\nYoung fashion designers vie for the chance t...,"Stars:Renato Lopez, Emilio Agu...",6,25.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
7708,The Sinner,2017–,"Crime,Drama,Mystery",7.2,\nAmbrose looks into Jamie and Nick's relation...,Director:Adam Bernstein| Stars:Bill Pu...,"1,373",45.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
5880,Unbreakable Kimmy Schmidt: Season 2 for Your C...,2016 TV Movie,NaN,5.8,\nAdd a Plot\n,"Stars:Drew Beasley, Sammy Voit...",10,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
4812,Jigeum Uri Hakgyoneun,2021–,"Drama,Fantasy,Horror",NaN,\nThe story of a group of students stuck in th...,"Stars:Yi-Hyun Cho, Ji-hu Park,...",NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
2512,2020 Golden Globe Awards,2020 TV Special,Comedy,7.2,\nComedian Ricky Gervais brutally roasts Holly...,Director:Louis J. Horvitz| Stars:Ricky...,703,134.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
5599,Danny Says,2015,"Documentary,Biography,History",6.7,\nDanny Says is a documentary on the life and ...,Director:Brendan Toller| Stars:Mx Just...,779,105.0,$0.04M,Movie,...,0,0,0,0,0,0,0,0,0,0
8213,Black Lightning,2017–2021,"Action,Drama,Sci-Fi",7.5,\nBlack Lightning faces off against Gravedigger.,Director:Salim Akil| Stars:Cress Willi...,311,42.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0

In [27]:
df.shape

(9999, 21449)

In [28]:
df.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,Director_Àlex Pastor,Director_Álex de la Iglesia,Director_Álvaro Brechner,Director_Álvaro Fernández Armero,Director_Álvaro Longoria,Director_Ángel Gómez Hernández,Director_Ángeles Reiné,Director_Åke Sandgren,Director_Óscar Pedraza,Director_Ömer Ugur
6121,The Umbilical Brothers: The Rehearsal,2014 Video,Comedy,8.9,\nThe outrageous comedy duo uses elements of m...,"Directors:David Collins, Shane Dundas, Jim...",16,92.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
3167,Amar y Vivir,2020–,"Drama,Romance",7.0,"\nIrene, the lead singer of the market place b...","Stars:Ana María Estupiñán, Car...",123,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
3774,Apache: La vida de Carlos Tevez,2019,"Biography,Crime,Drama",6.6,\nThis gritty dramatization of the life of Car...,"Stars:Balthazar Murillo, Vanes...","1,426",NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
2660,On the Verge,2021–,Comedy,NaN,\nA look a life for a group of women in their ...,"Stars:Julie Delpy, Sarah Jones...",NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
7165,Bridgerton,2020–,"Drama,Romance",8.1,\nTo fend off rumors about their garden escapa...,Director:Sheree Folkson| Stars:Adjoa A...,"1,905",61.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
4345,La femme la plus assassinée du monde,2018,"Biography,Drama,Mystery",5.3,\nPaula Maxa is the Parisian Grand Guignol The...,Director:Franck Ribière| Stars:Eric Go...,990,102.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
7033,La Reina de Indias y el Conquistador,2020–,"Drama,History",NaN,\nAlonso asks Manolo to make a decision based ...,"Stars:Emmanuel Esparza, Essine...",NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
9855,Surviving Summer,2022–,Drama,NaN,\nAdd a Plot\n,"Director:Ben Chessell| Stars:Sky Katz,...",NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
5082,Ya-soo,2006,"Action,Crime,Drama",6.3,\nJang is a homicide detective who likes to us...,Director:Seong-soo Kim| Stars:Sang-Woo...,794,124.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
1599,I Am the Pretty Thing That Lives in the House,2016,"Drama,Horror,Mystery",4.6,\nA young nurse takes care of an elderly autho...,Director:Oz Perkins| Stars:Ruth Wilson...,"13,685",89.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0

One-Line

In [29]:
df["ONE-LINE"] = df["ONE-LINE"].str.replace('\n', '', regex=False)
df["ONE-LINE"] = np.where(df["ONE-LINE"] == "Add a Plot", np.nan, df["ONE-LINE"])
df.sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,Director_Àlex Pastor,Director_Álex de la Iglesia,Director_Álvaro Brechner,Director_Álvaro Fernández Armero,Director_Álvaro Longoria,Director_Ángel Gómez Hernández,Director_Ángeles Reiné,Director_Åke Sandgren,Director_Óscar Pedraza,Director_Ömer Ugur
1052,Dark Places,2015,"Crime,Drama,Mystery",6.2,Libby Day was only eight years old when her fa...,Director:Gilles Paquet-Brenner| Stars:...,"43,273",113.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
8612,Too Hot to Handle,2020–,"Game-Show,Reality-TV,Romance",3.8,Host Desiree Burch connects with this season's...,"Stars:David Birtwistle, Desire...",155,41.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
7860,She-Ra and the Princesses of Power,2018–2020,"Animation,Action,Adventure",7.9,With tensions rising between Glimmer and Adora...,Director:Christina Manrique| Stars:Aim...,905,24.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
7511,Mighty Little Bheem,2019–,"Animation,Short,Adventure",NaN,NaN,"Directors:Rajiv Chilaka, Krishna Mohan Chi...",NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
7698,Anne,2017–2019,"Drama,Family",9.2,A dance rehearsal generates sparks (and tension).,Director:Paul Fox| Stars:Amybeth McNul...,"1,556",44.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
7518,Mighty Little Bheem,2019–,"Animation,Short,Adventure",NaN,NaN,"Directors:Rajiv Chilaka, Krishna Mohan Chi...",NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
8085,The Boondocks,2005–2014,"Animation,Action,Comedy",7.7,Riley displays most of his worst traits as he ...,"Directors:Dan Fausett, Bob Hathcock, Seung...",208,22.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
1583,"Bom Dia, Verônica",2020–,"Crime,Drama,Mystery",7.6,"After witnessing a suicide, an unobtrusive pol...","Stars:Tainá Müller, Camila Mor...","2,893",49.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
5223,The Love Section,2013,"Comedy,Drama,Romance",5.9,"Ali (Lawrence Adisa), is a struggling real est...",Director:Ronnie Warner| Stars:Mekhi Ph...,314,100.0,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
9730,Masters of the Universe: Revelation,2021–,"Animation,Action,Adventure",NaN,NaN,"Stars:Chris Wood, Dennis Haysb...",NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0

## Missing Data

In [30]:
columns_to_check = ['ONE-LINE', 'MOVIES', 'RATING', 'VOTES', 
                    'RunTime', 'Gross', 'TYPE', 'YEAR_FROM', 'YEAR_TO','GENRE']

missing_df = df[columns_to_check].isnull().sum().to_frame()
missing_df = missing_df.rename(columns={0: 'Missing Count'})
missing_df['missing_percentage'] = (missing_df['Missing Count'] / len(df)) * 100 #shape[0]
missing_df

           Missing Count  missing_percentage
ONE-LINE            1265           12.651265
MOVIES                 0            0.000000
RATING              1820           18.201820
VOTES               1820           18.201820
RunTime             2958           29.582958
Gross               9539           95.399540
TYPE                   0            0.000000
YEAR_FROM            644            6.440644
YEAR_TO             3824           38.243824
GENRE                 80            0.800080

YEAR_TO

In [31]:
df['YEAR_TO'].dtypes

In [32]:
#Take the current year
current_year = pd.Timestamp.now().year

df["YEAR_TO"] = np.where(
    df["YEAR_FROM"].notna() & df["YEAR_TO"].isna(),
    current_year,
    df["YEAR_TO"]
)

In [33]:
missing_df = df[columns_to_check].isnull().sum().to_frame()
missing_df

              0
ONE-LINE   1265
MOVIES        0
RATING     1820
VOTES      1820
RunTime    2958
Gross      9539
TYPE          0
YEAR_FROM   644
YEAR_TO     644
GENRE        80

Run-Time

In [34]:
df["RunTime"].describe()

count    7041.000000
mean       68.688539
std        47.258056
min         1.000000
25%        36.000000
50%        60.000000
75%        95.000000
max       853.000000
Name: RunTime, dtype: float64

In [35]:
df[df['RunTime'] >= 600]

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,Director_Àlex Pastor,Director_Álex de la Iglesia,Director_Álvaro Brechner,Director_Álvaro Fernández Armero,Director_Álvaro Longoria,Director_Ángel Gómez Hernández,Director_Ángeles Reiné,Director_Åke Sandgren,Director_Óscar Pedraza,Director_Ömer Ugur
1081,Soupçons,2004–2018,"Documentary,Crime,Drama",7.9,The high-profile murder trial of American nove...,"Stars:Michael Peterson, David ...","20,200",629.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
1902,El tiempo entre costuras,2013–2014,"Adventure,Drama,History",8.3,Sira Quiroga is a young Spanish dressmaker eng...,"Stars:Adriana Ugarte, Mari Car...","3,876",853.0,NaN,Series,...,0,0,0,0,0,0,0,0,0,0

In [36]:
df[df["RunTime"].isna()].sample(10)

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,Director_Àlex Pastor,Director_Álex de la Iglesia,Director_Álvaro Brechner,Director_Álvaro Fernández Armero,Director_Álvaro Longoria,Director_Ángel Gómez Hernández,Director_Ángeles Reiné,Director_Åke Sandgren,Director_Óscar Pedraza,Director_Ömer Ugur
1413,Persuasion,2022,"Drama,Romance",NaN,Based on the novel by Jane Austen,Director:Carrie Cracknell| Stars:Henry...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
8093,Fast & Furious Spy Racers,2019–,"Animation,Action,Crime",7.8,"When the crew takes over an amazing spy plane,...","Director:Leo Riley| Stars:Tyler Posey,...",69,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
4392,Amazing Interiors,2018–,Documentary,6.7,Tours through houses with interesting and spec...,"Stars:Wesley Cannon, Nicholas ...",723,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
9739,Centaurworld,2021–,"Animation,Adventure,Comedy",NaN,NaN,"Stars:Parvesh Cheena, Chris Di...",NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
5990,Cobra Kai: The Rise of Agni Kai,2020 TV Special,Action,NaN,NaN,Director:Jovan Taylor| Stars:Natalie B...,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
7223,Family Business,2019–,Comedy,7.4,"When his plans for the shop hit a snag, Joseph...",Director:Igor Gotesman| Stars:Jonathan...,82,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
6991,La Reina de Indias y el Conquistador,2020–,"Drama,History",NaN,Badillo agrees to help Catalina find her tribe...,"Stars:Emmanuel Esparza, Essine...",NaN,NaN,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
5288,42 días en la oscuridad,NaN,"Crime,Drama,Mystery",NaN,A Woman's Struggle to Find the Whereabouts of ...,"Stars:Aline Küppenheim, Claudi...",NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
6029,Liss Pereira: Reteniendo Liquidos,2019 TV Special,Comedy,6.4,Stand up comedy from the Colombian Liss Pereir...,Star:Liss Pereira,86,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
5825,The Outlaw Ocean,NaN,"Action,Adventure,Crime",NaN,A vigilante crew hunts down illegal poachers a...,,NaN,NaN,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0

In [37]:
df["RunTime"][df["TYPE"] == "Series"].describe()

count    2876.000000
mean       39.269471
std        29.580547
min         1.000000
25%        24.000000
50%        38.000000
75%        47.000000
max       853.000000
Name: RunTime, dtype: float64

In [38]:
df["RunTime"][df["TYPE"] == "Movie"].describe()

count    4165.000000
mean       89.002881
std        46.488210
min         1.000000
25%        63.000000
50%        90.000000
75%       105.000000
max       573.000000
Name: RunTime, dtype: float64

In [39]:
movie_mean_runtime = df.loc[df["TYPE"] == "Movie", "RunTime"].mean()
df.loc[(df["TYPE"] == "Movie")&(df["RunTime"].isna()), "RunTime"] = movie_mean_runtime

In [40]:
movie_mean_runtime

np.float64(89.00288115246099)

In [41]:
df["RunTime"][df["TYPE"] == "Movie"].isna().sum()

np.int64(0)

In [42]:
series_mean_runtime = df.loc[df["TYPE"] == "Series", "RunTime"].mean()
series_mean_runtime

np.float64(39.26947148817803)

In [43]:
df.loc[(df["TYPE"] == "Series")&(df["RunTime"].isna()), "RunTime"] = series_mean_runtime

In [44]:
df["RunTime"][df["TYPE"] == "Series"].isna().sum()

np.int64(0)

In [45]:
df["VOTES"] = df["VOTES"].str.replace(",", "", regex=False)
df.head()

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross,TYPE,...,Director_Àlex Pastor,Director_Álex de la Iglesia,Director_Álvaro Brechner,Director_Álvaro Fernández Armero,Director_Álvaro Longoria,Director_Ángel Gómez Hernández,Director_Ángeles Reiné,Director_Åke Sandgren,Director_Óscar Pedraza,Director_Ömer Ugur
0,Blood Red Sky,2021,"Action,Horror,Thriller",6.1,A woman with a mysterious illness is forced in...,Director:Peter Thorwarth| Stars:Peri B...,21062,121.000000,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0
1,Masters of the Universe: Revelation,2021–,"Animation,Action,Adventure",5.0,The war for Eternia begins again in what may b...,"Stars:Chris Wood, Sarah Michel...",17870,25.000000,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
2,The Walking Dead,2010–2022,"Drama,Horror,Thriller",8.2,Sheriff Deputy Rick Grimes wakes up from a com...,"Stars:Andrew Lincoln, Norman R...",885805,44.000000,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
3,Rick and Morty,2013–,"Animation,Adventure,Comedy",9.2,An animated series that follows the exploits o...,"Stars:Justin Roiland, Chris Pa...",414849,23.000000,NaN,Series,...,0,0,0,0,0,0,0,0,0,0
4,Army of Thieves,2021,"Action,Crime,Horror",NaN,"A prequel, set before the events of Army of th...",Director:Matthias Schweighöfer| Stars:...,NaN,89.002881,NaN,Movie,...,0,0,0,0,0,0,0,0,0,0

In [46]:
df = df.dropna(subset=["GENRE", "RATING", "YEAR_FROM", "YEAR_TO"])

In [47]:
column_names = ["MOVIES", "GENRE", "RATING", "ONE-LINE",
                "STARS", "VOTES", "RunTime", "Gross", "TYPE",
                "YEAR_FROM", "YEAR_TO"]
missing_df = df[column_names].isna().sum().to_frame()
missing_df = missing_df.rename(columns={0:"missing"})
missing_df["percentage"] = (missing_df["missing"] / df.shape[0]) * 100
missing_df

           missing  percentage
MOVIES           0    0.000000
GENRE            0    0.000000
RATING           0    0.000000
ONE-LINE       371    4.542116
STARS            0    0.000000
VOTES            0    0.000000
RunTime          0    0.000000
Gross         7708   94.368266
TYPE             0    0.000000
YEAR_FROM        0    0.000000
YEAR_TO          0    0.000000

In [49]:
df.drop(columns=["MOVIES", "YEAR", "GENRE", "STARS", "ONE-LINE", "Gross",
                 "Directors", "Actors"], inplace=True)